from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from dbmanager import DBManager, PrintManager

class Ui_Dialog_Branch(object):
    
    def setToday(self):
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        
    def reset(self):
        self.cBox_name.setCurrentIndex(-1)
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        for i in self.cboxs:
            i.setCurrentIndex(0)
        for i in self.sboxs:
            i.setValue(0)
        for i in self.sboxs_sv:
            i.setValue(0)
        self.lineEdit_cashin.setText("0")
        self.lineEdit_etc.setText("")
        self.lineEdit_etc_1.setText("")
        self.lineEdit_etc_2.setText("")
        self.lineEdit_etc_3.setText("")
        self.lineEdit_etc_4.setText("")
        self.lineEdit_etc_5.setText("")
        self.lineEdit_etc_6.setText("")
        self.lineEdit_etc_7.setText("")
        self.lineEdit_etc_8.setText("")
        self.lineEdit_etc_9.setText("")
        self.lineEdit_etc_10.setText("")
        self.cBox_percent_1.setCurrentIndex(0)
        self.cBox_percent_2.setCurrentIndex(0)
        self.cBox_percent_3.setCurrentIndex(0)
        self.cBox_percent_4.setCurrentIndex(0)
        self.cBox_percent_5.setCurrentIndex(0)
        self.cBox_percent_6.setCurrentIndex(0)
        self.cBox_percent_7.setCurrentIndex(0)
        self.cBox_percent_8.setCurrentIndex(0)
        self.cBox_percent_9.setCurrentIndex(0)
        self.cBox_percent_10.setCurrentIndex(0)
        for i in range(0, 14):
            self.labels[i].setText(f"{self.jisas[i]}:")

    def check_cBox(self):
        for i in range(0, 10):
            if self.cboxs[i].currentText() != "" and self.sboxs[i].value() == 0:
                return True
            if self.cboxs[i].currentText() == "" and self.sboxs[i].value() != 0:
                return True
        return False
    
    def set_lineEdit(self):
        txt = self.lineEdit_cashin.text().replace(',','')
        if self.lineEdit_cashin.text() != "":
            self.lineEdit_cashin.setText(format(int(txt), ','))
        else:
            self.lineEdit_cashin.setText("0")
    
    def calc_sales(self, cb, sv1, sv2, pc):
        if cb.currentText() != "" and sv1.value() != 0:
            self.pname = cb.currentText()
            self.query = "Select price from productinfo where product = ?"
            self.result = self.dbManager.cursor.execute(self.query, self.pname)
            for i in self.result:
                self.get_price = i[0]
            self.carc_price= round((int(sv1.value())-int(sv2.value()))*(self.get_price*float(pc.currentText())))
            self.total_price.append(self.carc_price)
        else:
            self.total_price.append(0)
            
    def calc_Product(self):
        del self.total_price[:]
        self.dbManager.connect()
        for i in range(0, 10):
            self.calc_sales(self.cboxs[i], self.sboxs[i], self.sboxs_sv[i], self.percents[i])
        self.label_3.setText(f"금액: {format(sum(self.total_price), ',')}")
        self.dbManager.close()

    def search_misu(self):
        self.dbManager.connect()
        for i in range(0, 14):
            self.query = "Select sum(Sales), sum(Cashin) from Branch where Name = ?"
            try:
                self.dbManager.cursor.execute(self.query, self.jisas[i])
                self.result = self.dbManager.cursor.fetchall()
                for j in self.result:
                    if j[0] != None:
                        self.total_sales = j[0]
                    else:
                        self.total_sales = "0"
                    if j[1] != None:
                        self.total_cashin = j[1]
                    else:
                        self.total_cashin = "0"
                    self.labels[i].setText(f"{self.jisas[i]}:    {format(int(self.total_sales)-int(self.total_cashin),',')}")
            except:
                self.labels[i].setText(f"{self.jisas[i]}:    0")

    def insert_product(self):
        if self.cBox_name.currentText() == "":
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("지사를 선택하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        elif self.check_cBox():
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품이나 제품 개수를 확인하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        else:
            self.name = self.cBox_name.currentText()
            self.pin = '0'
            self.date = self.dateEdit.date().toString('yyyy-MM-dd')
            self.cash_in = self.lineEdit_cashin.text().replace(',','')
            self.etc = self.lineEdit_etc.text()
            self.dbManager.connect()
            
            for i in range(0, 10):
                if self.cboxs[i].currentText() != "":
                    self.product = self.cboxs[i].currentText()
                    self.pout = str(self.sboxs[i].value())
                    self.sv = str(self.sboxs_sv[i].value())
                    self.etcc = self.lines[i].text()
                    self.query = "Insert into store (Date, Product, Pin, Pout, Etcc) VALUES(?,?,?,?,?)"
                    self.dbManager.cursor.execute(self.query, (self.date, self.product, self.pin, self.pout, self.name))
                    self.dbManager.conn.commit()
                    
                    self.percent = self.percents[i].currentText()
                    self.query = "Select price from productinfo where product = ?"
                    self.result = self.dbManager.cursor.execute(self.query, self.product)
                    for k in self.result:
                        self.get_price = k[0]
                    self.carc_price = round((int(self.pout)-int(self.sv)) * int(self.get_price) * float(self.percent))
                    
                    self.query = "Insert into Branch (Date, Name, Product, Pout, Sales, Percentage, Etcc) VALUES(?,?,?,?,?,?,?)"
                    self.dbManager.cursor.execute(self.query, (self.date, self.name, self.product, self.pout, str(self.carc_price), self.percent, self.etcc))
                    self.dbManager.conn.commit()
                
            if self.lineEdit_cashin.text() != "0":
                self.query = "Insert into Branch (Date, Name, Cashin, Etcc) VALUES(?,?,?,?)"
                self.dbManager.cursor.execute(self.query, (self.date, self.name, self.cash_in, self.etc))
                self.dbManager.conn.commit()
            
            msg = QMessageBox()
            msg.setWindowTitle("입력완료")
            msg.setText("입력 되었습니다.")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec()
            self.dbManager.close()
            self.reset()
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1096, 721)
        self.cBox_product_9 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_9.setGeometry(QtCore.QRect(60, 560, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_9.setFont(font)
        self.cBox_product_9.setObjectName("cBox_product_9")
        self.cBox_product_1 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_1.setGeometry(QtCore.QRect(60, 160, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_1.setFont(font)
        self.cBox_product_1.setObjectName("cBox_product_1")
        self.cBox_product_7 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_7.setGeometry(QtCore.QRect(60, 460, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_7.setFont(font)
        self.cBox_product_7.setObjectName("cBox_product_7")
        self.cBox_product_2 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_2.setGeometry(QtCore.QRect(60, 210, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_2.setFont(font)
        self.cBox_product_2.setObjectName("cBox_product_2")
        self.btn_insert = QtWidgets.QPushButton(Dialog, clicked = self.insert_product)
        self.btn_insert.setGeometry(QtCore.QRect(630, 50, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_insert.setFont(font)
        self.btn_insert.setAutoDefault(False)
        self.btn_insert.setDefault(False)
        self.btn_insert.setFlat(False)
        self.btn_insert.setObjectName("btn_insert")

        self.btn_misu = QtWidgets.QPushButton(Dialog, clicked = self.search_misu)
        self.btn_misu.setGeometry(QtCore.QRect(870, 50, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_misu.setFont(font)
        self.btn_misu.setAutoDefault(False)
        self.btn_misu.setDefault(False)
        self.btn_misu.setFlat(False)
        self.btn_misu.setObjectName("btn_misu")

        self.cBox_product_4 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_4.setGeometry(QtCore.QRect(60, 310, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_4.setFont(font)
        self.cBox_product_4.setObjectName("cBox_product_4")
        self.cBox_percent_4 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_4.setGeometry(QtCore.QRect(430, 310, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_4.setFont(font)
        self.cBox_percent_4.setObjectName("cBox_percent_4")
        self.sBox_product_1 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_1.setGeometry(QtCore.QRect(515, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_1.setFont(font)
        self.sBox_product_1.setMaximum(999)
        self.sBox_product_1.setObjectName("sBox_product_1")
        self.cBox_product_5 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_5.setGeometry(QtCore.QRect(60, 360, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_5.setFont(font)
        self.cBox_product_5.setObjectName("cBox_product_5")
        self.cBox_percent_7 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_7.setGeometry(QtCore.QRect(430, 460, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_7.setFont(font)
        self.cBox_percent_7.setObjectName("cBox_percent_7")
        self.cBox_name = QtWidgets.QComboBox(Dialog)
        self.cBox_name.setGeometry(QtCore.QRect(80, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_name.setFont(font)
        self.cBox_name.setObjectName("cBox_name")
        self.cBox_percent_10 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_10.setGeometry(QtCore.QRect(430, 610, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_10.setFont(font)
        self.cBox_percent_10.setObjectName("cBox_percent_10")
        self.cBox_product_6 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_6.setGeometry(QtCore.QRect(60, 410, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_6.setFont(font)
        self.cBox_product_6.setObjectName("cBox_product_6")
        self.cBox_product_8 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_8.setGeometry(QtCore.QRect(60, 510, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_8.setFont(font)
        self.cBox_product_8.setObjectName("cBox_product_8")
        self.cBox_product_10 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_10.setGeometry(QtCore.QRect(60, 610, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_10.setFont(font)
        self.cBox_product_10.setObjectName("cBox_product_10")
        self.cBox_percent_5 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_5.setGeometry(QtCore.QRect(430, 360, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_5.setFont(font)
        self.cBox_percent_5.setObjectName("cBox_percent_5")
        self.cBox_product_3 = QtWidgets.QComboBox(Dialog)
        self.cBox_product_3.setGeometry(QtCore.QRect(60, 260, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_3.setFont(font)
        self.cBox_product_3.setObjectName("cBox_product_3")
        self.lineEdit_cashin = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_cashin.setGeometry(QtCore.QRect(370, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_cashin.setFont(font)
        self.lineEdit_cashin.setObjectName("lineEdit_cashin")
        self.lineEdit_cashin.setValidator(QtGui.QIntValidator())
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(310, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.cBox_percent_3 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_3.setGeometry(QtCore.QRect(430, 260, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_3.setFont(font)
        self.cBox_percent_3.setObjectName("cBox_percent_3")
        self.cBox_percent_1 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_1.setGeometry(QtCore.QRect(430, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_1.setFont(font)
        self.cBox_percent_1.setObjectName("cBox_percent_1")
        self.cBox_percent_6 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_6.setGeometry(QtCore.QRect(430, 410, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_6.setFont(font)
        self.cBox_percent_6.setObjectName("cBox_percent_6")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(100, 40, 121, 41))
        self.dateEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self._today_button = QtWidgets.QPushButton('&오늘', clicked=self.setToday)
        self.dateEdit.calendarWidget().layout().addWidget(self._today_button)
        self.dateEdit.wheelEvent = lambda event: None
        self.dbManager = DBManager()
        self.printManager = PrintManager()
        self.total_price = []
        self.cBox_percent_8 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_8.setGeometry(QtCore.QRect(430, 510, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_8.setFont(font)
        self.cBox_percent_8.setObjectName("cBox_percent_8")
        self.cBox_percent_2 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_2.setGeometry(QtCore.QRect(430, 210, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_2.setFont(font)
        self.cBox_percent_2.setObjectName("cBox_percent_2")
        self.cBox_percent_9 = QtWidgets.QComboBox(Dialog)
        self.cBox_percent_9.setGeometry(QtCore.QRect(430, 560, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_9.setFont(font)
        self.cBox_percent_9.setObjectName("cBox_percent_9")
        self.lineEdit_etc = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc.setGeometry(QtCore.QRect(370, 100, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc.setFont(font)
        self.lineEdit_etc.setText("")
        self.lineEdit_etc.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_1.setGeometry(QtCore.QRect(640, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_1.setFont(font)
        self.lineEdit_etc_1.setText("")
        self.lineEdit_etc_1.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_2.setGeometry(QtCore.QRect(640, 210, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_2.setFont(font)
        self.lineEdit_etc_2.setText("")
        self.lineEdit_etc_2.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_3.setGeometry(QtCore.QRect(640, 260, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_3.setFont(font)
        self.lineEdit_etc_3.setText("")
        self.lineEdit_etc_3.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_4.setGeometry(QtCore.QRect(640, 310, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_4.setFont(font)
        self.lineEdit_etc_4.setText("")
        self.lineEdit_etc_4.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_5.setGeometry(QtCore.QRect(640, 360, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_5.setFont(font)
        self.lineEdit_etc_5.setText("")
        self.lineEdit_etc_5.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_6.setGeometry(QtCore.QRect(640, 410, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_6.setFont(font)
        self.lineEdit_etc_6.setText("")
        self.lineEdit_etc_6.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_7.setGeometry(QtCore.QRect(640, 460, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_7.setFont(font)
        self.lineEdit_etc_7.setText("")
        self.lineEdit_etc_7.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_8.setGeometry(QtCore.QRect(640, 510, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_8.setFont(font)
        self.lineEdit_etc_8.setText("")
        self.lineEdit_etc_8.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_9.setGeometry(QtCore.QRect(640, 560, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_9.setFont(font)
        self.lineEdit_etc_9.setText("")
        self.lineEdit_etc_9.setObjectName("lineEdit_etc")
        
        self.lineEdit_etc_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_etc_10.setGeometry(QtCore.QRect(640, 610, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc_10.setFont(font)
        self.lineEdit_etc_10.setText("")
        self.lineEdit_etc_10.setObjectName("lineEdit_etc")
        
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 100, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(450, 660, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 660, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(520, 130, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(591, 130, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")


        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(850, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(850, 190, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(833, 230, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(850, 270, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")

        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(850, 310, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")

        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(833, 350, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(850, 390, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")

        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(850, 430, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")

        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(850, 470, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(850, 510, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")

        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(850, 550, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")

        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(850, 590, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")

        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(886, 630, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")

        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(886, 670, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        
        self.sBox_product_2 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_2.setGeometry(QtCore.QRect(515, 210, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_2.setFont(font)
        self.sBox_product_2.setMaximum(999)
        self.sBox_product_2.setObjectName("sBox_product_2")
        self.sBox_product_3 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_3.setGeometry(QtCore.QRect(515, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_3.setFont(font)
        self.sBox_product_3.setMaximum(999)
        self.sBox_product_3.setObjectName("sBox_product_3")
        self.sBox_product_4 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_4.setGeometry(QtCore.QRect(515, 310, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_4.setFont(font)
        self.sBox_product_4.setMaximum(999)
        self.sBox_product_4.setObjectName("sBox_product_4")
        self.sBox_product_5 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_5.setGeometry(QtCore.QRect(515, 360, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_5.setFont(font)
        self.sBox_product_5.setMaximum(999)
        self.sBox_product_5.setObjectName("sBox_product_5")
        self.sBox_product_6 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_6.setGeometry(QtCore.QRect(515, 410, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_6.setFont(font)
        self.sBox_product_6.setMaximum(999)
        self.sBox_product_6.setObjectName("sBox_product_6")
        self.sBox_product_7 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_7.setGeometry(QtCore.QRect(515, 460, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_7.setFont(font)
        self.sBox_product_7.setMaximum(999)
        self.sBox_product_7.setObjectName("sBox_product_7")
        self.sBox_product_8 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_8.setGeometry(QtCore.QRect(515, 510, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_8.setFont(font)
        self.sBox_product_8.setMaximum(999)
        self.sBox_product_8.setObjectName("sBox_product_8")
        self.sBox_product_9 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_9.setGeometry(QtCore.QRect(515, 560, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_9.setFont(font)
        self.sBox_product_9.setMaximum(999)
        self.sBox_product_9.setObjectName("sBox_product_9")
        self.sBox_product_10 = QtWidgets.QSpinBox(Dialog)
        self.sBox_product_10.setGeometry(QtCore.QRect(515, 610, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_10.setFont(font)
        self.sBox_product_10.setMaximum(999)
        self.sBox_product_10.setObjectName("sBox_product_10")

        self.sBox_sv_1 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_1.setGeometry(QtCore.QRect(580, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_1.setFont(font)
        self.sBox_sv_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_1.setMaximum(999)
        self.sBox_sv_1.setObjectName("sBox_sv_1")

        self.sBox_sv_2 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_2.setGeometry(QtCore.QRect(580, 210, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_2.setFont(font)
        self.sBox_sv_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_2.setMaximum(999)
        self.sBox_sv_2.setObjectName("sBox_sv_2")

        self.sBox_sv_3 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_3.setGeometry(QtCore.QRect(580, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_3.setFont(font)
        self.sBox_sv_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_3.setMaximum(999)
        self.sBox_sv_3.setObjectName("sBox_sv_3")

        self.sBox_sv_4 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_4.setGeometry(QtCore.QRect(580, 310, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_4.setFont(font)
        self.sBox_sv_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_4.setMaximum(999)
        self.sBox_sv_4.setObjectName("sBox_sv_4")

        self.sBox_sv_5 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_5.setGeometry(QtCore.QRect(580, 360, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_5.setFont(font)
        self.sBox_sv_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_5.setMaximum(999)
        self.sBox_sv_5.setObjectName("sBox_sv_5")

        self.sBox_sv_6 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_6.setGeometry(QtCore.QRect(580, 410, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_6.setFont(font)
        self.sBox_sv_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_6.setMaximum(999)
        self.sBox_sv_6.setObjectName("sBox_sv_6")

        self.sBox_sv_7 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_7.setGeometry(QtCore.QRect(580, 460, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_7.setFont(font)
        self.sBox_sv_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_7.setMaximum(999)
        self.sBox_sv_7.setObjectName("sBox_sv_7")

        self.sBox_sv_8 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_8.setGeometry(QtCore.QRect(580, 510, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_8.setFont(font)
        self.sBox_sv_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_8.setMaximum(999)
        self.sBox_sv_8.setObjectName("sBox_sv_8")

        self.sBox_sv_9 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_9.setGeometry(QtCore.QRect(580, 560, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_9.setFont(font)
        self.sBox_sv_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_9.setMaximum(999)
        self.sBox_sv_9.setObjectName("sBox_sv_9")

        self.sBox_sv_10 = QtWidgets.QSpinBox(Dialog)
        self.sBox_sv_10.setGeometry(QtCore.QRect(580, 610, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_10.setFont(font)
        self.sBox_sv_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_10.setMaximum(999)
        self.sBox_sv_10.setObjectName("sBox_sv_10")


        
        self.cboxs = [self.cBox_product_1, self.cBox_product_2, self.cBox_product_3, self.cBox_product_4, self.cBox_product_5,
                      self.cBox_product_6, self.cBox_product_7, self.cBox_product_8, self.cBox_product_9, self.cBox_product_10]
        self.sboxs = [self.sBox_product_1, self.sBox_product_2, self.sBox_product_3, self.sBox_product_4, self.sBox_product_5, 
                      self.sBox_product_6, self.sBox_product_7, self.sBox_product_8, self.sBox_product_9, self.sBox_product_10]
        self.lines = [self.lineEdit_etc_1, self.lineEdit_etc_2, self.lineEdit_etc_3, self.lineEdit_etc_4, self.lineEdit_etc_5,
                      self.lineEdit_etc_6, self.lineEdit_etc_7, self.lineEdit_etc_8, self.lineEdit_etc_9, self.lineEdit_etc_10]
        self.sboxs_sv = [self.sBox_sv_1, self.sBox_sv_2, self.sBox_sv_3, self.sBox_sv_4, self.sBox_sv_5,
                         self.sBox_sv_6, self.sBox_sv_7, self.sBox_sv_8, self.sBox_sv_9, self.sBox_sv_10]
        self.percents = [self.cBox_percent_1, self.cBox_percent_2, self.cBox_percent_3, self.cBox_percent_4, self.cBox_percent_5,
                         self.cBox_percent_6, self.cBox_percent_7, self.cBox_percent_8, self.cBox_percent_9, self.cBox_percent_10]
        self.cBox_name.wheelEvent = lambda event: None
        for i in self.cboxs:
            i.wheelEvent = lambda event: None
        for i in self.sboxs:
            i.wheelEvent = lambda event: None
        for i in self.sboxs_sv:
            i.wheelEvent = lambda event: None
        self.cBox_percent_1.wheelEvent = lambda event: None
        self.cBox_percent_2.wheelEvent = lambda event: None
        self.cBox_percent_3.wheelEvent = lambda event: None
        self.cBox_percent_4.wheelEvent = lambda event: None
        self.cBox_percent_5.wheelEvent = lambda event: None
        self.cBox_percent_6.wheelEvent = lambda event: None
        self.cBox_percent_7.wheelEvent = lambda event: None
        self.cBox_percent_8.wheelEvent = lambda event: None
        self.cBox_percent_9.wheelEvent = lambda event: None
        self.cBox_percent_10.wheelEvent = lambda event: None

        self.jisas = ['석촌지사', '광주지사', '빛고을지사', '상인지사', '신흥지사', '북수원지사', '성내지사', 
                      '태양지사', '태능지사', '이천지사', '청구상가', '연제', '기타', '미림지사']
        self.labels = [self.label_11, self.label_12, self.label_13, self.label_14, self.label_15, self.label_16, self.label_17, 
                       self.label_18, self.label_19, self.label_20, self.label_21, self.label_22, self.label_23, self.label_24]
        
        for i in self.cboxs:
            i.currentIndexChanged['int'].connect(self.calc_Product)
        for i in self.percents:
            i.currentIndexChanged['int'].connect(self.calc_Product)
        for i in self.sboxs:
            i.valueChanged['int'].connect(self.calc_Product)
        for i in self.sboxs_sv:
            i.valueChanged['int'].connect(self.calc_Product)
        
        self.lineEdit_cashin.editingFinished.connect(self.set_lineEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_insert.setText(_translate("Dialog", "입력"))
        self.btn_misu.setText(_translate("Dialog", "누적미수"))
        self.lineEdit_cashin.setText(_translate("Dialog", "0"))
        self.label_1.setText(_translate("Dialog", "입금:"))
        self.label_2.setText(_translate("Dialog", "비고:"))
        self.label_3.setText(_translate("Dialog", "금액:"))
        self.label_4.setText(_translate("Dialog", "*덕용제품 출고시 0.300 적용"))
        self.label_5.setText(_translate("Dialog", "출고"))
        self.label_6.setText(_translate("Dialog", "덤"))
        self.label_11.setText(_translate("Dialog", "석촌지사:"))
        self.label_12.setText(_translate("Dialog", "광주지사:"))
        self.label_13.setText(_translate("Dialog", "빛고을지사:"))
        self.label_14.setText(_translate("Dialog", "상인지사:"))
        self.label_15.setText(_translate("Dialog", "신흥지사:"))
        self.label_16.setText(_translate("Dialog", "북수원지사:"))
        self.label_17.setText(_translate("Dialog", "성내지사:"))
        self.label_18.setText(_translate("Dialog", "태양지사:"))
        self.label_19.setText(_translate("Dialog", "태능지사:"))
        self.label_20.setText(_translate("Dialog", "이천지사:"))
        self.label_21.setText(_translate("Dialog", "청구지사:"))
        self.label_22.setText(_translate("Dialog", "연제:"))
        self.label_23.setText(_translate("Dialog", "기타:"))
        self.label_24.setText(_translate("Dialog", "미림지사:"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_Branch()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
