from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from dbmanager import DBManager


class Ui_Dialog_Bonsa(object):
    
    def setToday(self):
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        
    def reset(self):
        self.cBox_name.setCurrentIndex(0)
        self.lineEdit_cashin.setText("0")
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        for i in self.cboxs:
            i.setCurrentIndex(0)
        for i in self.sboxs:
            i.setValue(0)
        for i in self.sboxs_sv:
            i.setValue(0)
        self.cBox_percent_1.setCurrentIndex(0)
        self.cBox_percent_2.setCurrentIndex(0)
        self.cBox_percent_3.setCurrentIndex(0)
        self.cBox_percent_4.setCurrentIndex(0)
        self.cBox_percent_5.setCurrentIndex(0)
        self.cBox_percent_6.setCurrentIndex(0)
        self.cBox_percent_7.setCurrentIndex(0)
        self.cBox_percent_8.setCurrentIndex(0)
        self.cBox_percent_9.setCurrentIndex(0)
        self.cBox_percent_10.setCurrentIndex(0)
        for i in range(0, 2):
            self.labels[i].setText(f"{self.jisas[i]}:")
        
    def check_cBox(self):
        for i in range(0, 10):
            if self.cboxs[i].currentText() != "" and self.sboxs[i].value() == 0:
                return True
            if self.cboxs[i].currentText() == "" and self.sboxs[i].value() != 0:
                return True
        return False
    
    def calc_sales(self, cb, sv1, sv2, pc):
        if cb.currentText() != "" and sv1.value() != 0:
            self.pname = cb.currentText()
            self.query = "Select price from productinfo where product = ?"
            self.result = self.dbManager.cursor.execute(self.query, self.pname)
            for i in self.result:
                self.get_price = i[0]
            self.carc_price= round((int(sv1.value())-int(sv2.value()))*(self.get_price*float(pc.currentText())))
            self.total_price.append(self.carc_price)
        else:
            self.total_price.append(0)
    
    def calc_Product(self):
        del self.total_price[:]
        self.dbManager.connect()
        for i in range(0, 10):
            self.calc_sales(self.cboxs[i], self.sboxs[i], self.sboxs_sv[i], self.percents[i])
        self.label_calc.setText(f"{format(sum(self.total_price), ',')}")
        self.dbManager.close()
    
    def set_lineEdit(self):
        txt = self.lineEdit_cashin.text().replace(',','')
        if self.lineEdit_cashin.text() != "":
            self.lineEdit_cashin.setText(format(int(txt), ','))
        else:
            self.lineEdit_cashin.setText("0")

    def search_misu(self):
        self.dbManager.connect()
        for i in range(0, 2):
            self.query = "Select sum(Price), sum(Cashin) from Bonsa where Name = ?"
            try:
                self.dbManager.cursor.execute(self.query, self.jisas[i])
                self.result = self.dbManager.cursor.fetchall()
                for j in self.result:
                    if j[0] != None:
                        self.total_sales = j[0]
                    else:
                        self.total_sales = "0"
                    if j[1] != None:
                        self.total_cashin = j[1]
                    else:
                        self.total_cashin = "0"
                    self.labels[i].setText(f"{self.jisas[i]}:    {format(int(self.total_sales)-int(self.total_cashin),',')}")
            except:
                self.labels[i].setText(f"{self.jisas[i]}:    0")

    
    def insert_product(self):
        if self.cBox_name.currentText() == "":
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("본사명을 선택하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        elif self.check_cBox():
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품이나 제품 개수를 확인하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        else:
            self.name = self.cBox_name.currentText()
            self.pout = '0'
            self.date = self.dateEdit.date().toString('yyyy-MM-dd')
            self.cash_in = self.lineEdit_cashin.text().replace(',','')
            self.dbManager.connect()
            
            for i in range(0, 10):
                if self.cboxs[i].currentText() != "":
                    self.product = self.cboxs[i].currentText()
                    self.pin = str(self.sboxs[i].value())
                    self.sv = str(self.sboxs_sv[i].value())
                    self.query = "Insert into store (Date, Product, Pin, Pout, Etcc) VALUES(?,?,?,?,?)"
                    self.dbManager.cursor.execute(self.query, (self.date, self.product, self.pin, self.pout, self.name))
                    self.dbManager.conn.commit()
                    
                    self.percent = self.percents[i].currentText()
                    self.query = "Select price from productinfo where product = ?"
                    self.result = self.dbManager.cursor.execute(self.query, self.product)
                    for k in self.result:
                        self.get_price = k[0]
                    self.carc_price = round((int(self.pin)-int(self.sv)) * int(self.get_price)* float(self.percent))
                    
                    self.query = "Insert into Bonsa (Date, Name, Product, Pin, Price, Percentage) VALUES(?,?,?,?,?,?)"
                    self.dbManager.cursor.execute(self.query, (self.date, self.name, self.product, self.pin, str(self.carc_price), self.percent))
                    self.dbManager.conn.commit()
            
            if self.lineEdit_cashin.text() != "0":
                self.query = "Insert into Bonsa (Date, Name, Cashin) VALUES(?,?,?)"
                self.dbManager.cursor.execute(self.query, (self.date, self.name, self.cash_in))
                self.dbManager.conn.commit()
            
            self.dbManager.close()
            msg = QMessageBox()
            msg.setWindowTitle("입력완료")
            msg.setText("입력 되었습니다.")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec()
            self.reset()
        
    
    def setupUi(self, Dialog_Bonsa):
        Dialog_Bonsa.setObjectName("Dialog_Bonsa")
        Dialog_Bonsa.resize(852, 735)
        Dialog_Bonsa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBox_percent_9 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_9.setGeometry(QtCore.QRect(410, 600, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_9.setFont(font)
        self.cBox_percent_9.setObjectName("cBox_percent_9")
        self.sBox_product_6 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_6.setGeometry(QtCore.QRect(500, 450, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_6.setFont(font)
        self.sBox_product_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_6.setMaximum(999)
        self.sBox_product_6.setObjectName("sBox_product_6")
        self.cBox_product_9 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_9.setGeometry(QtCore.QRect(40, 600, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_9.setFont(font)
        self.cBox_product_9.setObjectName("cBox_product_9")
        self.cBox_product_5 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_5.setGeometry(QtCore.QRect(40, 400, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_5.setFont(font)
        self.cBox_product_5.setObjectName("cBox_product_5")
        self.sBox_product_9 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_9.setGeometry(QtCore.QRect(500, 600, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_9.setFont(font)
        self.sBox_product_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_9.setMaximum(999)
        self.sBox_product_9.setObjectName("sBox_product_9")
        self.cBox_product_7 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_7.setGeometry(QtCore.QRect(40, 500, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_7.setFont(font)
        self.cBox_product_7.setObjectName("cBox_product_7")
        self.cBox_product_1 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_1.setGeometry(QtCore.QRect(40, 200, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_1.setFont(font)
        self.cBox_product_1.setObjectName("cBox_product_1")
        self.sBox_product_1 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_1.setGeometry(QtCore.QRect(500, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_1.setFont(font)
        self.sBox_product_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_1.setMaximum(999)
        self.sBox_product_1.setObjectName("sBox_product_1")
        self.cBox_name = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_name.setGeometry(QtCore.QRect(200, 84, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_name.setFont(font)
        self.cBox_name.setObjectName("cBox_name")
        self.cBox_name.addItem("")
        self.cBox_name.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(Dialog_Bonsa)
        self.dateEdit.setGeometry(QtCore.QRect(40, 84, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self._today_button = QtWidgets.QPushButton('&오늘', clicked=self.setToday)
        self.dateEdit.calendarWidget().layout().addWidget(self._today_button)
        self.dateEdit.wheelEvent = lambda event: None
        self.dbManager = DBManager()
        self.total_price = []

        self.lineEdit_cashin = QtWidgets.QLineEdit(Dialog_Bonsa)
        self.lineEdit_cashin.setGeometry(QtCore.QRect(160, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_cashin.setFont(font)
        self.lineEdit_cashin.setObjectName("lineEdit_cashin")
        self.lineEdit_cashin.setValidator(QtGui.QIntValidator())

        self.label_cashin = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_cashin.setGeometry(QtCore.QRect(100, 152, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_cashin.setFont(font)
        self.label_cashin.setObjectName("label_cashin")
        
        self.cBox_product_4 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_4.setGeometry(QtCore.QRect(40, 350, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_4.setFont(font)
        self.cBox_product_4.setObjectName("cBox_product_4")
        self.sBox_product_3 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_3.setGeometry(QtCore.QRect(500, 300, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_3.setFont(font)
        self.sBox_product_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_3.setMaximum(999)
        self.sBox_product_3.setObjectName("sBox_product_3")
        self.sBox_product_2 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_2.setGeometry(QtCore.QRect(500, 250, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_2.setFont(font)
        self.sBox_product_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_2.setMaximum(999)
        self.sBox_product_2.setObjectName("sBox_product_2")
        self.sBox_product_10 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_10.setGeometry(QtCore.QRect(500, 650, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_10.setFont(font)
        self.sBox_product_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_10.setMaximum(999)
        self.sBox_product_10.setObjectName("sBox_product_10")
        self.cBox_product_8 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_8.setGeometry(QtCore.QRect(40, 550, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_8.setFont(font)
        self.cBox_product_8.setObjectName("cBox_product_8")
        self.cBox_percent_2 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_2.setGeometry(QtCore.QRect(410, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_2.setFont(font)
        self.cBox_percent_2.setObjectName("cBox_percent_2")
        self.cBox_product_3 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_3.setGeometry(QtCore.QRect(40, 300, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_3.setFont(font)
        self.cBox_product_3.setObjectName("cBox_product_3")
        self.sBox_product_7 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_7.setGeometry(QtCore.QRect(500, 500, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_7.setFont(font)
        self.sBox_product_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_7.setMaximum(999)
        self.sBox_product_7.setObjectName("sBox_product_7")
        self.cBox_percent_1 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_1.setGeometry(QtCore.QRect(410, 200, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_1.setFont(font)
        self.cBox_percent_1.setObjectName("cBox_percent_1")
        self.cBox_percent_8 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_8.setGeometry(QtCore.QRect(410, 550, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_8.setFont(font)
        self.cBox_percent_8.setObjectName("cBox_percent_8")
        self.sBox_product_5 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_5.setGeometry(QtCore.QRect(500, 400, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_5.setFont(font)
        self.sBox_product_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_5.setMaximum(999)
        self.sBox_product_5.setObjectName("sBox_product_5")
        self.sBox_product_8 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_8.setGeometry(QtCore.QRect(500, 550, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_8.setFont(font)
        self.sBox_product_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_8.setMaximum(999)
        self.sBox_product_8.setObjectName("sBox_product_8")
        self.cBox_percent_10 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_10.setGeometry(QtCore.QRect(410, 650, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_10.setFont(font)
        self.cBox_percent_10.setObjectName("cBox_percent_10")
        self.cBox_percent_7 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_7.setGeometry(QtCore.QRect(410, 500, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_7.setFont(font)
        self.cBox_percent_7.setObjectName("cBox_percent_7")
        self.cBox_product_10 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_10.setGeometry(QtCore.QRect(40, 650, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_10.setFont(font)
        self.cBox_product_10.setObjectName("cBox_product_10")
        self.sBox_product_4 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_product_4.setGeometry(QtCore.QRect(500, 350, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_4.setFont(font)
        self.sBox_product_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_4.setMaximum(999)
        self.sBox_product_4.setObjectName("sBox_product_4")
        self.cBox_product_6 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_6.setGeometry(QtCore.QRect(40, 450, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_6.setFont(font)
        self.cBox_product_6.setObjectName("cBox_product_6")
        self.cBox_percent_5 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_5.setGeometry(QtCore.QRect(410, 400, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_5.setFont(font)
        self.cBox_percent_5.setObjectName("cBox_percent_5")
        self.cBox_percent_6 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_6.setGeometry(QtCore.QRect(410, 450, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_6.setFont(font)
        self.cBox_percent_6.setObjectName("cBox_percent_6")
        self.cBox_product_2 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_product_2.setGeometry(QtCore.QRect(40, 250, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_2.setFont(font)
        self.cBox_product_2.setObjectName("cBox_product_2")
        self.btn_insert = QtWidgets.QPushButton(Dialog_Bonsa, clicked = self.insert_product)
        self.btn_insert.setGeometry(QtCore.QRect(410, 100, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_insert.setFont(font)
        self.btn_insert.setAutoDefault(False)
        self.btn_insert.setDefault(False)
        self.btn_insert.setFlat(False)
        self.btn_insert.setObjectName("btn_insert")

        self.btn_misu = QtWidgets.QPushButton(Dialog_Bonsa, clicked = self.search_misu)
        self.btn_misu.setGeometry(QtCore.QRect(650, 100, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_misu.setFont(font)
        self.btn_misu.setAutoDefault(False)
        self.btn_misu.setDefault(False)
        self.btn_misu.setFlat(False)
        self.btn_misu.setObjectName("btn_misu")

        self.label_11 = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_11.setGeometry(QtCore.QRect(660, 200, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_12.setGeometry(QtCore.QRect(650, 250, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.cBox_percent_4 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_4.setGeometry(QtCore.QRect(410, 350, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_4.setFont(font)
        self.cBox_percent_4.setObjectName("cBox_percent_4")
        self.cBox_percent_3 = QtWidgets.QComboBox(Dialog_Bonsa)
        self.cBox_percent_3.setGeometry(QtCore.QRect(410, 300, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_percent_3.setFont(font)
        self.cBox_percent_3.setObjectName("cBox_percent_3")
        self.label_3 = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_4.setGeometry(QtCore.QRect(510, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.sBox_sv_1 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_1.setGeometry(QtCore.QRect(570, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_1.setFont(font)
        self.sBox_sv_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_1.setMaximum(999)
        self.sBox_sv_1.setObjectName("sBox_sv_1")
        self.sBox_sv_2 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_2.setGeometry(QtCore.QRect(570, 250, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_2.setFont(font)
        self.sBox_sv_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_2.setMaximum(999)
        self.sBox_sv_2.setObjectName("sBox_sv_2")
        self.sBox_sv_3 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_3.setGeometry(QtCore.QRect(570, 300, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_3.setFont(font)
        self.sBox_sv_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_3.setMaximum(999)
        self.sBox_sv_3.setObjectName("sBox_sv_3")
        self.sBox_sv_4 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_4.setGeometry(QtCore.QRect(570, 350, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_4.setFont(font)
        self.sBox_sv_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_4.setMaximum(999)
        self.sBox_sv_4.setObjectName("sBox_sv_4")
        self.sBox_sv_5 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_5.setGeometry(QtCore.QRect(570, 400, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_5.setFont(font)
        self.sBox_sv_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_5.setMaximum(999)
        self.sBox_sv_5.setObjectName("sBox_sv_5")
        self.sBox_sv_6 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_6.setGeometry(QtCore.QRect(570, 450, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_6.setFont(font)
        self.sBox_sv_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_6.setMaximum(999)
        self.sBox_sv_6.setObjectName("sBox_sv_6")
        self.sBox_sv_7 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_7.setGeometry(QtCore.QRect(570, 500, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_7.setFont(font)
        self.sBox_sv_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_7.setMaximum(999)
        self.sBox_sv_7.setObjectName("sBox_sv_7")
        self.sBox_sv_8 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_8.setGeometry(QtCore.QRect(570, 550, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_8.setFont(font)
        self.sBox_sv_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_8.setMaximum(999)
        self.sBox_sv_8.setObjectName("sBox_sv_8")
        self.sBox_sv_9 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_9.setGeometry(QtCore.QRect(570, 600, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_9.setFont(font)
        self.sBox_sv_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_9.setMaximum(999)
        self.sBox_sv_9.setObjectName("sBox_sv_9")
        self.sBox_sv_10 = QtWidgets.QSpinBox(Dialog_Bonsa)
        self.sBox_sv_10.setGeometry(QtCore.QRect(570, 650, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_10.setFont(font)
        self.sBox_sv_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_sv_10.setMaximum(999)
        self.sBox_sv_10.setObjectName("sBox_sv_10")
        self.label_1 = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_1.setGeometry(QtCore.QRect(310, 700, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_calc = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_calc.setGeometry(QtCore.QRect(370, 700, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_calc.setFont(font)
        self.label_calc.setObjectName("label_calc")
        self.label_5 = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_5.setGeometry(QtCore.QRect(40, 700, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog_Bonsa)
        self.label_6.setGeometry(QtCore.QRect(580, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        
        self.cboxs = [self.cBox_product_1, self.cBox_product_2, self.cBox_product_3, self.cBox_product_4, self.cBox_product_5,
                      self.cBox_product_6, self.cBox_product_7, self.cBox_product_8, self.cBox_product_9, self.cBox_product_10]
        self.sboxs = [self.sBox_product_1, self.sBox_product_2, self.sBox_product_3, self.sBox_product_4, self.sBox_product_5, 
                      self.sBox_product_6, self.sBox_product_7, self.sBox_product_8, self.sBox_product_9, self.sBox_product_10]
        self.sboxs_sv = [self.sBox_sv_1, self.sBox_sv_2, self.sBox_sv_3, self.sBox_sv_4, self.sBox_sv_5,
                         self.sBox_sv_6, self.sBox_sv_7, self.sBox_sv_8, self.sBox_sv_9, self.sBox_sv_10]
        self.percents = [self.cBox_percent_1, self.cBox_percent_2, self.cBox_percent_3, self.cBox_percent_4, self.cBox_percent_5,
                         self.cBox_percent_6, self.cBox_percent_7, self.cBox_percent_8, self.cBox_percent_9, self.cBox_percent_10]
        self.cBox_name.wheelEvent = lambda event: None
        for i in self.cboxs:
            i.wheelEvent = lambda event: None
        for i in self.sboxs:
            i.wheelEvent = lambda event: None
        for i in self.sboxs_sv:
            i.wheelEvent = lambda event: None
        self.cBox_percent_1.wheelEvent = lambda event: None
        self.cBox_percent_2.wheelEvent = lambda event: None
        self.cBox_percent_3.wheelEvent = lambda event: None
        self.cBox_percent_4.wheelEvent = lambda event: None
        self.cBox_percent_5.wheelEvent = lambda event: None
        self.cBox_percent_6.wheelEvent = lambda event: None
        self.cBox_percent_7.wheelEvent = lambda event: None
        self.cBox_percent_8.wheelEvent = lambda event: None
        self.cBox_percent_9.wheelEvent = lambda event: None
        self.cBox_percent_10.wheelEvent = lambda event: None

        self.jisas = ['생앤', '백옥생']
        self.labels = [self.label_11, self.label_12]
        
        for i in self.cboxs:
            i.currentIndexChanged['int'].connect(self.calc_Product)
        for i in self.percents:
            i.currentIndexChanged['int'].connect(self.calc_Product)
        for i in self.sboxs:
            i.valueChanged['int'].connect(self.calc_Product)
        for i in self.sboxs_sv:
            i.valueChanged['int'].connect(self.calc_Product)

        self.lineEdit_cashin.editingFinished.connect(self.set_lineEdit)

        self.retranslateUi(Dialog_Bonsa)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Bonsa)

    def retranslateUi(self, Dialog_Bonsa):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Bonsa.setWindowTitle(_translate("Dialog_Bonsa", "Dialog"))
        self.cBox_name.setItemText(0, _translate("Dialog_Bonsa", "생앤"))
        self.cBox_name.setItemText(1, _translate("Dialog_Bonsa", "백옥생"))
        self.lineEdit_cashin.setText(_translate("Dialog", "0"))
        self.btn_insert.setText(_translate("Dialog_Bonsa", "입력"))
        self.btn_misu.setText(_translate("Dialog", "누적미수"))
        self.label_3.setText(_translate("Dialog_Bonsa", "본사 입고"))
        self.label_4.setText(_translate("Dialog_Bonsa", "입고"))
        self.label_1.setText(_translate("Dialog_Bonsa", "금액: "))
        self.label_cashin.setText(_translate("Dialog_Bonsa", "입금: "))
        self.label_calc.setText(_translate("Dialog_Bonsa", "0"))
        self.label_5.setText(_translate("Dialog_Bonsa", "*덕용제품 입고시 0.250 적용"))
        self.label_6.setText(_translate("Dialog_Bonsa", "덤"))
        self.label_11.setText(_translate("Dialog", "생앤:"))
        self.label_12.setText(_translate("Dialog", "백옥생:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Bonsa = QtWidgets.QDialog()
    ui = Ui_Dialog_Bonsa()
    ui.setupUi(Dialog_Bonsa)
    Dialog_Bonsa.show()
    sys.exit(app.exec_())
