from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from dbmanager import DBManager, PrintManager
from filemanager import FileManager
from dateutil import relativedelta
import openpyxl
import datetime
import os

class Ui_Dialog_Payslip(object):

    def setToday_1(self):
        self.dateEdit_1.setDate(QtCore.QDate.currentDate())
        
    def setToday_2(self):
        self.dateEdit_2.setDate(QtCore.QDate.currentDate())

    def reset(self):
        self.cBox_name.setCurrentIndex(-1)
        self.tableWidget.clearContents()
        self.sBox_product_1.setValue(0)
        self.lineEdit_shop.setText("0")
        self.lineEdit_special.setText("0")
        self.lineEdit_sv.setText("0")
        self.label_deposit.setText("적금:")

    def set_lineEdit(self):
        for i in self.lines:
            txt = i.text().replace(',','')
            if i.text() != "":
                i.setText(format(int(txt), ','))
            else:
                i.setText("0")

    def search_payslip(self):
        self.date1 = self.dateEdit_1.date().toString('yyyy-MM-dd')
        self.date2 = self.dateEdit_2.date().toString('yyyy-MM-dd')
        self.selected_year = int(self.dateEdit_1.date().toString('yyyy'))
        self.selected_month = int(self.dateEdit_1.date().toString('MM'))
        self.name = self.cBox_name.currentText()
        self.label_deposit.setText("적금:")
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(1)

        self.dbManager.connect()

        self.query = "Select Name, Dsales, DRefund, DCashin, DCardin, TTin, DBit, TBit-DBit, TBit from (select Name, sum(Sales) as DSales, sum(Refund) as DRefund, sum(Cashin) as DCashin, sum(Cardin) as DCardin, sum(Cashin)+sum(Cardin) as TTin, sum(Sales)-sum(Cashin)-sum(Cardin)-sum(Refund) as DBit from Staff where Date between ? and ? and Name = ? group by Name) a, (select sum(Sales)-sum(Refund)-sum(Cashin)-sum(Cardin) as TBit from Staff where Date between '2019-01-01' and ? and Name = ?) b"
        self.dbManager.cursor.execute(self.query, (self.date1, self.date2, self.name, self.date2, self.name))
        self.rows = self.dbManager.cursor.fetchall()

        self.tbrow = 0
        for i in self.rows:
            item = QtWidgets.QTableWidgetItem(str(i[0]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 0, item)
            item = QtWidgets.QTableWidgetItem(format(i[1], ','))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 1, item)
            item = QtWidgets.QTableWidgetItem(format(i[2], ','))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 2, item)
            item = QtWidgets.QTableWidgetItem(format(i[3], ','))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 3, item)
            item = QtWidgets.QTableWidgetItem(format(i[4], ','))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 4, item)
            item = QtWidgets.QTableWidgetItem(format(i[5], ','))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 5, item)
            item = QtWidgets.QTableWidgetItem(format(i[6], ','))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 6, item)
            item = QtWidgets.QTableWidgetItem(format(i[7], ','))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 7, item)
            item = QtWidgets.QTableWidgetItem(format(i[8], ','))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(self.tbrow, 8, item)
            self.tbrow += 1
        
        self.query = "SELECT * FROM Deposit WHERE Name = ?"
        rows = self.dbManager.cursor.execute(self.query, (self.name)).fetchall()
        for i in rows:
            today = datetime.date.today()
            xx = i[3].split('-')
            passed = i[2] + ((self.selected_year - int(xx[0])) * 12 + (self.selected_month - int(xx[1])))
            self.label_deposit.setText(f"{self.name}: {passed}회")
        self.dbManager.close()
    
    def insert_payslip(self):
        if self.tableWidget.item(0, 0) == None:
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("조회 하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
            return
        if self.tableWidget.item(0, 0).text() != self.cBox_name.currentText():
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("조회 대상과 선택한 이름이 다릅니다.")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
            return

        self.date1 = self.dateEdit_1.date().toString('yyyy-MM-dd')
        self.date2 = self.dateEdit_2.date().toString('yyyy-MM-dd')
        self.selected_year = self.dateEdit_1.date().toString('yyyy')
        self.selected_month = self.dateEdit_1.date().toString('MM')
        self.name = self.tableWidget.item(0, 0).text()
        self.names = list(self.tableWidget.item(0, 0).text())
        self.massage = self.sBox_product_1.value()
        self.special = self.lineEdit_special.text().replace(',','')
        self.shop = self.lineEdit_shop.text().replace(',','')
        self.sv = self.lineEdit_sv.text().replace(',','')
        self.passed = 0
        self.position = ""
        file_name = f"C:/samusil/급여명세서/{self.selected_year}_{self.selected_month}_{self.name}.xlsx"

        self.dbManager.connect()
        self.query = "SELECT * FROM Deposit WHERE Name = ?"
        rows = self.dbManager.cursor.execute(self.query, (self.name)).fetchall()
        for i in rows:
            today = datetime.date.today()
            basic_date = i[3].split('-')
            self.passed = i[2] + ((int(self.selected_year) - int(basic_date[0])) * 12 + (int(self.selected_month) - int(basic_date[1])))
            self.position = list(i[1])

        self.dbManager.close()

        try:
            self.wb = openpyxl.load_workbook(self.filename)
            sheet = self.wb.active
            sheet.cell(row=3, column=2).value = f"{self.selected_year}년  {self.selected_month}월   지 급 명 세 서"
            sheet.cell(row=5, column=4).value = self.names[0]+"    "+self.names[1]+"    "+self.names[2]
            sheet.cell(row=5, column=7).value = self.position[0] + "       " + self.position[1]
            if self.passed != 0:
                sheet.cell(row=19, column=3).value = "적금 {0}회".format(self.passed)
                sheet.cell(row=20, column=3).value = 100000
            if self.massage != 0:
                sheet.cell(row=19, column=4).value = "맛사지{0}명".format(self.massage)
                sheet.cell(row=20, column=4).value = self.massage * 5000

            sheet.cell(row=14, column=3).value = int(self.special)
            
            sheet.cell(row=26, column=3).value = self.tableWidget.item(0, 1).text()
            sheet.cell(row=26, column=4).value = self.tableWidget.item(0, 2).text()
            sheet.cell(row=26, column=5).value = self.tableWidget.item(0, 3).text()
            sheet.cell(row=26, column=6).value = self.tableWidget.item(0, 4).text()
            sheet.cell(row=28, column=7).value = self.tableWidget.item(0, 7).text()
            sheet.cell(row=28, column=8).value = self.tableWidget.item(0, 8).text()

            sheet.cell(row=28, column=3).value = int(self.shop)
            sheet.cell(row=28, column=4).value = int(self.sv)

            self.wb.save(file_name)

            msg = QMessageBox()
            msg.setWindowTitle("입력완료")
            msg.setText("입력 되었습니다.\n바로 인쇄 하시겠습니까?")
            msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            msg.setDefaultButton(QMessageBox.Yes)
            x = msg.exec()

            if x == QMessageBox.Yes:
                self.printManager.setprinter()
                os.startfile(file_name, "print")
            self.reset()
        except:
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("입력 실패")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        


    def setupUi(self, Dialog_Payslip):
        Dialog_Payslip.setObjectName("Dialog_Payslip")
        Dialog_Payslip.resize(1066, 553)
        Dialog_Payslip.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fManager = FileManager()
        self.dbManager = DBManager()
        self.printManager = PrintManager()
        self.filename = "C:/samusil/Payslip.xlsx"
        self.tableWidget = QtWidgets.QTableWidget(Dialog_Payslip)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1041, 181))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setColumnWidth(0, 80)
        self.tableWidget.setColumnWidth(1, 120)
        self.tableWidget.setColumnWidth(3, 110)
        self.tableWidget.setColumnWidth(4, 110)
        self.tableWidget.setColumnWidth(5, 120)
        self.tableWidget.setColumnWidth(6, 130)
        self.tableWidget.setColumnWidth(7, 130)
        self.tableWidget.setColumnWidth(8, 130)
        self.dbManager = DBManager()
        self.btn_insert = QtWidgets.QPushButton(Dialog_Payslip, clicked=self.insert_payslip)
        self.btn_insert.setGeometry(QtCore.QRect(670, 420, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_insert.setFont(font)
        self.btn_insert.setAutoDefault(False)
        self.btn_insert.setDefault(False)
        self.btn_insert.setFlat(False)
        self.btn_insert.setObjectName("btn_insert")
        self.label_11 = QtWidgets.QLabel(Dialog_Payslip)
        self.label_11.setGeometry(QtCore.QRect(320, 259, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.dateEdit_2 = QtWidgets.QDateEdit(Dialog_Payslip)
        self.dateEdit_2.setGeometry(QtCore.QRect(370, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setReadOnly(False)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.btn_search = QtWidgets.QPushButton(Dialog_Payslip, clicked=self.search_payslip)
        self.btn_search.setGeometry(QtCore.QRect(700, 240, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setAutoDefault(False)
        self.btn_search.setDefault(False)
        self.btn_search.setFlat(False)
        self.btn_search.setObjectName("btn_search")
        self.cBox_name = QtWidgets.QComboBox(Dialog_Payslip)
        self.cBox_name.setGeometry(QtCore.QRect(550, 255, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_name.setFont(font)
        self.cBox_name.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBox_name.setEditable(False)
        self.cBox_name.setModelColumn(0)
        self.cBox_name.addItems(self.fManager.payslip)
        self.cBox_name.setObjectName("cBox_name")
        self.dateEdit_1 = QtWidgets.QDateEdit(Dialog_Payslip)
        self.dateEdit_1.setGeometry(QtCore.QRect(190, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_1.setFont(font)
        self.dateEdit_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_1.setReadOnly(False)
        self.dateEdit_1.setCalendarPopup(True)
        self.dateEdit_1.setObjectName("dateEdit_1")
        self.label_deposit = QtWidgets.QLabel(Dialog_Payslip)
        self.label_deposit.setGeometry(QtCore.QRect(210, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_deposit.setFont(font)
        self.label_deposit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_deposit.setObjectName("label_deposit")
        self.label_massage = QtWidgets.QLabel(Dialog_Payslip)
        self.label_massage.setGeometry(QtCore.QRect(400, 340, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_massage.setFont(font)
        self.label_massage.setAlignment(QtCore.Qt.AlignCenter)
        self.label_massage.setObjectName("label_massage")
        self.label_shop = QtWidgets.QLabel(Dialog_Payslip)
        self.label_shop.setGeometry(QtCore.QRect(160, 430, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_shop.setFont(font)
        self.label_shop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shop.setObjectName("label_shop")
        self.label_sv = QtWidgets.QLabel(Dialog_Payslip)
        self.label_sv.setGeometry(QtCore.QRect(390, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sv.setFont(font)
        self.label_sv.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sv.setObjectName("label_sv")
        self.lineEdit_shop = QtWidgets.QLineEdit(Dialog_Payslip)
        self.lineEdit_shop.setGeometry(QtCore.QRect(240, 430, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_shop.setFont(font)
        self.lineEdit_shop.setObjectName("lineEdit_shop")
        self.lineEdit_sv = QtWidgets.QLineEdit(Dialog_Payslip)
        self.lineEdit_sv.setGeometry(QtCore.QRect(480, 430, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_sv.setFont(font)
        self.lineEdit_sv.setObjectName("lineEdit_sv")
        self.sBox_product_1 = QtWidgets.QSpinBox(Dialog_Payslip)
        self.sBox_product_1.setGeometry(QtCore.QRect(470, 340, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_1.setFont(font)
        self.sBox_product_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sBox_product_1.setMaximum(200)
        self.sBox_product_1.setObjectName("sBox_product_1")
        self.lineEdit_special = QtWidgets.QLineEdit(Dialog_Payslip)
        self.lineEdit_special.setGeometry(QtCore.QRect(650, 340, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_special.setFont(font)
        self.lineEdit_special.setObjectName("lineEdit_special")
        self.label_special = QtWidgets.QLabel(Dialog_Payslip)
        self.label_special.setGeometry(QtCore.QRect(560, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_special.setFont(font)
        self.label_special.setAlignment(QtCore.Qt.AlignCenter)
        self.label_special.setObjectName("label_special")

        date = datetime.date.today()
        rd = relativedelta.relativedelta
        firstdate = date + rd(day=1)
        lastdate = date + rd(day=31)
        predate = date - rd(months=1)
        prefirst = predate + rd(day=1)
        prelastdate = predate + rd(day=31)

        if date.day > 18:
            self.dateEdit_1.setDate(firstdate)
            self.dateEdit_2.setDate(lastdate)
        else:
            self.dateEdit_1.setDate(prefirst)
            self.dateEdit_2.setDate(prelastdate)

        self._today_button_1 = QtWidgets.QPushButton('&오늘', clicked=self.setToday_1)
        self.dateEdit_1.calendarWidget().layout().addWidget(self._today_button_1)
        self._today_button_2 = QtWidgets.QPushButton('&오늘', clicked=self.setToday_2)
        self.dateEdit_2.calendarWidget().layout().addWidget(self._today_button_2)

        self.dateEdit_1.wheelEvent = lambda event: None
        self.dateEdit_2.wheelEvent = lambda event: None
        self.cBox_name.wheelEvent = lambda event: None
        self.sBox_product_1.wheelEvent = lambda event: None

        self.lines = [self.lineEdit_special, self.lineEdit_shop, self.lineEdit_sv]
        for i in self.lines:
            i.editingFinished.connect(self.set_lineEdit)

        self.lineEdit_special.setValidator(QtGui.QIntValidator())
        self.lineEdit_shop.setValidator(QtGui.QIntValidator())
        self.lineEdit_sv.setValidator(QtGui.QIntValidator())

        self.retranslateUi(Dialog_Payslip)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Payslip)

    def retranslateUi(self, Dialog_Payslip):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Payslip.setWindowTitle(_translate("Dialog_Payslip", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Payslip", "이름"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Payslip", "매출"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_Payslip", "환불"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_Payslip", "현금입금"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_Payslip", "카드입금"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog_Payslip", "총입금합계"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog_Payslip", "기간미수"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog_Payslip", "전월미수"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog_Payslip", "누적미수"))
        self.btn_insert.setText(_translate("Dialog_Payslip", "입력"))
        self.label_11.setText(_translate("Dialog_Payslip", "~"))
        self.btn_search.setText(_translate("Dialog_Payslip", "조회"))
        self.label_deposit.setText(_translate("Dialog_Payslip", "적금:"))
        self.label_massage.setText(_translate("Dialog_Payslip", "마사지:"))
        self.label_shop.setText(_translate("Dialog_Payslip", "샵매출:"))
        self.label_sv.setText(_translate("Dialog_Payslip", "S/V매출:"))
        self.lineEdit_shop.setText(_translate("Dialog_Payslip", "0"))
        self.lineEdit_sv.setText(_translate("Dialog_Payslip", "0"))
        self.lineEdit_special.setText(_translate("Dialog_Payslip", "0"))
        self.label_special.setText(_translate("Dialog_Payslip", "추가수당:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Payslip = QtWidgets.QDialog()
    ui = Ui_Dialog_Payslip()
    ui.setupUi(Dialog_Payslip)
    Dialog_Payslip.show()
    sys.exit(app.exec_())
