from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from dbmanager import DBManager
from filemanager import FileManager

class Ui_Dialog_Add(object):
      
    def set_lineEdit(self):
        txt = self.lineEdit_price.text().replace(',','')
        if self.lineEdit_price.text() != "":
            self.lineEdit_price.setText(format(int(txt), ','))
        else:
            self.lineEdit_price.setText("0")
    
    def setupUi(self, Dialog_Add):
        Dialog_Add.setObjectName("Dialog_Add")
        Dialog_Add.resize(729, 458)
        Dialog_Add.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_3 = QtWidgets.QLabel(Dialog_Add)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dbManager = DBManager()
        self.fManager = FileManager()
        self.lineEdit_product = QtWidgets.QLineEdit(Dialog_Add)
        self.lineEdit_product.setGeometry(QtCore.QRect(100, 100, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_product.setFont(font)
        self.lineEdit_product.setText("")
        self.lineEdit_product.setObjectName("lineEdit_product")
        self.label_4 = QtWidgets.QLabel(Dialog_Add)
        self.label_4.setGeometry(QtCore.QRect(380, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_update_1 = QtWidgets.QLineEdit(Dialog_Add)
        self.lineEdit_update_1.setGeometry(QtCore.QRect(480, 100, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_update_1.setFont(font)
        self.lineEdit_update_1.setText("")
        self.lineEdit_update_1.setObjectName("lineEdit_update_1")
        self.lineEdit_update_2 = QtWidgets.QLineEdit(Dialog_Add)
        self.lineEdit_update_2.setGeometry(QtCore.QRect(480, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_update_2.setFont(font)
        self.lineEdit_update_2.setText("")
        self.lineEdit_update_2.setObjectName("lineEdit_update_2")
        self.label_5 = QtWidgets.QLabel(Dialog_Add)
        self.label_5.setGeometry(QtCore.QRect(30, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_price = QtWidgets.QLineEdit(Dialog_Add)
        self.lineEdit_price.setGeometry(QtCore.QRect(100, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_price.setFont(font)
        self.lineEdit_price.setText("")
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.lineEdit_price.editingFinished.connect(self.set_lineEdit)
        self.lineEdit_price.setText("0")
        self.lineEdit_price.setValidator(QtGui.QIntValidator())
        self.label_6 = QtWidgets.QLabel(Dialog_Add)
        self.label_6.setGeometry(QtCore.QRect(380, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_insert = QtWidgets.QPushButton(Dialog_Add)
        self.btn_insert.setGeometry(QtCore.QRect(170, 220, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_insert.setFont(font)
        self.btn_insert.setAutoDefault(False)
        self.btn_insert.setDefault(False)
        self.btn_insert.setFlat(False)
        self.btn_insert.setObjectName("btn_insert")
        self.btn_update = QtWidgets.QPushButton(Dialog_Add)
        self.btn_update.setGeometry(QtCore.QRect(520, 220, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_update.setFont(font)
        self.btn_update.setAutoDefault(False)
        self.btn_update.setDefault(False)
        self.btn_update.setFlat(False)
        self.btn_update.setObjectName("btn_update")
        self.btn_delete = QtWidgets.QPushButton(Dialog_Add)
        self.btn_delete.setGeometry(QtCore.QRect(340, 376, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setAutoDefault(False)
        self.btn_delete.setDefault(False)
        self.btn_delete.setFlat(False)
        self.btn_delete.setObjectName("btn_delete")
        self.cBox_product = QtWidgets.QComboBox(Dialog_Add)
        self.cBox_product.setGeometry(QtCore.QRect(30, 380, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product.setFont(font)
        self.cBox_product.setObjectName("cBox_product")
        self.label = QtWidgets.QLabel(Dialog_Add)
        self.label.setGeometry(QtCore.QRect(120, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_Add)
        self.label_2.setGeometry(QtCore.QRect(450, 30, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.cBox_product.wheelEvent = lambda event: None

        self.retranslateUi(Dialog_Add)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Add)

    def retranslateUi(self, Dialog_Add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Add.setWindowTitle(_translate("Dialog_Add", "Dialog"))
        self.label_3.setText(_translate("Dialog_Add", "제품명:"))
        self.label_4.setText(_translate("Dialog_Add", "현재 제품명:"))
        self.label_5.setText(_translate("Dialog_Add", "가격:"))
        self.label_6.setText(_translate("Dialog_Add", "바꿀 제품명:"))
        self.btn_insert.setText(_translate("Dialog_Add", "추가"))
        self.btn_update.setText(_translate("Dialog_Add", "수정"))
        self.btn_delete.setText(_translate("Dialog_Add", "삭제"))
        self.label.setText(_translate("Dialog_Add", "제품 추가"))
        self.label_2.setText(_translate("Dialog_Add", "기존 재고 제품명 수정"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Add = QtWidgets.QDialog()
    ui = Ui_Dialog_Add()
    ui.setupUi(Dialog_Add)
    Dialog_Add.show()
    sys.exit(app.exec_())
