from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from dbmanager import DBManager, PrintManager
import os

class Ui_Dialog_Details(object):
    
    def setToday_1(self):
        self.dateEdit_1.setDate(QtCore.QDate.currentDate())
        
    def setToday_2(self):
        self.dateEdit_2.setDate(QtCore.QDate.currentDate())
    
    def del_details(self):
        try:
            self.selected = self.tableWidget.item(self.tableWidget.currentRow(), 0).text()
            self.selected_row = self.tableWidget.currentRow()
            self.dbManager.connect()
            self.query = "delete from Staff where id = ?"
            self.dbManager.cursor.execute(self.query, (self.selected))
            self.dbManager.conn.commit()
            self.dbManager.close()
            self.tableWidget.removeRow(self.selected_row)
            msg = QMessageBox()
            msg.setWindowTitle("삭제완료")
            msg.setText("삭제 되었습니다.")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec()
        except:
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("삭제할 항목을 선택하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
    
    def search_details(self):
        self.date1 = self.dateEdit_1.date().toString('yyyy-MM-dd')
        self.date2 = self.dateEdit_2.date().toString('yyyy-MM-dd')
        self.name = self.cBox_name.currentText()
        
        if self.name == "전체":
            self.tableWidget.clearContents()
            self.dbManager.connect()
            
            self.query = "Select id, Date, Name, Sales, Refund, Cashin, Cardin, Etcc, Number, Cardkind from Staff where Date between ? and ? order by Date, id"
            self.dbManager.cursor.execute(self.query, self.date1, self.date2)
            self.rows = self.dbManager.cursor.fetchall()
            self.tableWidget.setRowCount(len(self.rows))

            self.tbrow = 0
            for i in self.rows:
                item = QtWidgets.QTableWidgetItem(str(i[0]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 0, item)
                item = QtWidgets.QTableWidgetItem(str(i[1]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 1, item)
                item = QtWidgets.QTableWidgetItem(str(i[2]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 2, item)
                item = QtWidgets.QTableWidgetItem(format(i[3], ','))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 3, item)
                item = QtWidgets.QTableWidgetItem(format(i[4], ','))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 4, item)
                item = QtWidgets.QTableWidgetItem(format(i[5], ','))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 5, item)
                item = QtWidgets.QTableWidgetItem(format(i[6], ','))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 6, item)
                item = QtWidgets.QTableWidgetItem(str(i[7]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 7, item)
                item = QtWidgets.QTableWidgetItem(str(i[8]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 8, item)
                item = QtWidgets.QTableWidgetItem(str(i[9]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 9, item)
                self.tbrow += 1

            self.dbManager.close()
            
        else:
            self.tableWidget.clearContents()
            self.dbManager.connect()
            
            self.query = "Select id, Date, Name, Sales, Refund, Cashin, Cardin, Etcc, Number, Cardkind from Staff where Date between ? and ? and Name = ? order by Date, id"
            self.dbManager.cursor.execute(self.query, (self.date1, self.date2, self.name))
            self.rows = self.dbManager.cursor.fetchall()
            self.tableWidget.setRowCount(len(self.rows))

            self.tbrow = 0
            for i in self.rows:
                item = QtWidgets.QTableWidgetItem(str(i[0]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 0, item)
                item = QtWidgets.QTableWidgetItem(str(i[1]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 1, item)
                item = QtWidgets.QTableWidgetItem(str(i[2]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 2, item)
                item = QtWidgets.QTableWidgetItem(format(i[3], ','))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 3, item)
                item = QtWidgets.QTableWidgetItem(format(i[4], ','))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 4, item)
                item = QtWidgets.QTableWidgetItem(format(i[5], ','))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 5, item)
                item = QtWidgets.QTableWidgetItem(format(i[6], ','))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 6, item)
                item = QtWidgets.QTableWidgetItem(str(i[7]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 7, item)
                item = QtWidgets.QTableWidgetItem(str(i[8]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 8, item)
                item = QtWidgets.QTableWidgetItem(str(i[9]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(self.tbrow, 9, item)
                self.tbrow += 1
            
            self.dbManager.close()
    
    def pprint(self):
        if self.tableWidget.item(0, 0) == None:
            return
        self.date1 = self.dateEdit_1.date().toString('yyyy-MM-dd')
        self.date2 = self.dateEdit_2.date().toString('yyyy-MM-dd')
        self.name = self.cBox_name.currentText()
        self.printManager.setprinter()
        self.directory = "C:/samusil/"
        self.file_name = self.directory + "detail.txt"
        f = open(self.file_name, 'w')
        f.write("기간:  "+self.date1+"  ~  "+self.date2)
        f.write("\n----일자-------이름------------출고-----환불------현금입금----카드입금----------\n")
        for row in range(self.tableWidget.rowCount()):
            s1 = self.tableWidget.item(row, 1).text()
            s2 = self.tableWidget.item(row, 2).text()
            s3 = self.tableWidget.item(row, 3).text()
            s4 = self.tableWidget.item(row, 4).text()
            s5 = self.tableWidget.item(row, 5).text()
            s6 = self.tableWidget.item(row, 6).text()
            f.write(s1+"   "+s2+"\t"+s3+"\t"+s4+"\t"+s5+"\t"+s6+"\n")
        f.write("-----------------------------------------------------------------------------------------")
        os.startfile(self.file_name, "print")
        f.close()
            
    
    def setupUi(self, Dialog_Details):
        Dialog_Details.setObjectName("Dialog_Details")
        Dialog_Details.resize(1240, 845)
        self.btn_print = QtWidgets.QPushButton(Dialog_Details, clicked = self.pprint)
        self.btn_print.setGeometry(QtCore.QRect(1010, 740, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_print.setFont(font)
        self.btn_print.setAutoDefault(False)
        self.btn_print.setDefault(False)
        self.btn_print.setFlat(False)
        self.btn_print.setObjectName("btn_print")
        
        self.dbManager = DBManager()
        self.printManager = PrintManager()
        self.dateEdit_2 = QtWidgets.QDateEdit(Dialog_Details)
        self.dateEdit_2.setGeometry(QtCore.QRect(500, 750, 121, 41))
        self.dateEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setReadOnly(False)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.cBox_name = QtWidgets.QComboBox(Dialog_Details)
        self.cBox_name.setGeometry(QtCore.QRect(670, 754, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_name.setFont(font)
        self.cBox_name.setEditable(False)
        self.cBox_name.setModelColumn(0)
        self.cBox_name.setObjectName("cBox_name")
        self.tableWidget = QtWidgets.QTableWidget(Dialog_Details)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 1211, 661))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setColumnWidth(1, 110)
        self.tableWidget.setColumnWidth(3, 130)
        self.tableWidget.setColumnWidth(4, 110)
        self.tableWidget.setColumnWidth(5, 130)
        self.tableWidget.setColumnWidth(6, 130)
        self.tableWidget.setColumnWidth(7, 150)
        self.tableWidget.setColumnWidth(8, 120)
        self.label_11 = QtWidgets.QLabel(Dialog_Details)
        self.label_11.setGeometry(QtCore.QRect(450, 759, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.btn_delete = QtWidgets.QPushButton(Dialog_Details, clicked = self.del_details)
        self.btn_delete.setGeometry(QtCore.QRect(50, 760, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setAutoDefault(False)
        self.btn_delete.setDefault(False)
        self.btn_delete.setFlat(False)
        self.btn_delete.setObjectName("btn_delete")
        self.dateEdit_1 = QtWidgets.QDateEdit(Dialog_Details)
        self.dateEdit_1.setGeometry(QtCore.QRect(320, 750, 121, 41))
        self.dateEdit_1.setFocusPolicy(QtCore.Qt.NoFocus)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_1.setFont(font)
        self.dateEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_1.setReadOnly(False)
        self.dateEdit_1.setCalendarPopup(True)
        self.dateEdit_1.setObjectName("dateEdit_1")
        
        self.dateEdit_1.setDate(QtCore.QDate.currentDate())
        self.dateEdit_2.setDate(QtCore.QDate.currentDate())
        self._today_button_1 = QtWidgets.QPushButton('&오늘', clicked=self.setToday_1)
        self.dateEdit_1.calendarWidget().layout().addWidget(self._today_button_1)
        self._today_button_2 = QtWidgets.QPushButton('&오늘', clicked=self.setToday_2)
        self.dateEdit_2.calendarWidget().layout().addWidget(self._today_button_2)
        
        self.btn_search = QtWidgets.QPushButton(Dialog_Details, clicked=self.search_details)
        self.btn_search.setGeometry(QtCore.QRect(820, 740, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setAutoDefault(False)
        self.btn_search.setDefault(False)
        self.btn_search.setFlat(False)
        self.btn_search.setObjectName("btn_search")
        
        self.dateEdit_1.wheelEvent = lambda event: None
        self.dateEdit_2.wheelEvent = lambda event: None
        self.cBox_name.wheelEvent = lambda event: None

        self.retranslateUi(Dialog_Details)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Details)

    def retranslateUi(self, Dialog_Details):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Details.setWindowTitle(_translate("Dialog_Details", "Dialog"))
        self.btn_print.setText(_translate("Dialog_Details", "프린트"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Details", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Details", "날짜"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_Details", "이름"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_Details", "매출"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_Details", "환불"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog_Details", "현금입금"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog_Details", "카드입금"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog_Details", "기타"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog_Details", "승인번호"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog_Details", "카드사"))
        self.label_11.setText(_translate("Dialog_Details", "~"))
        self.btn_delete.setText(_translate("Dialog_Details", "삭제"))
        self.btn_search.setText(_translate("Dialog_Details", "조회"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Details = QtWidgets.QDialog()
    ui = Ui_Dialog_Details()
    ui.setupUi(Dialog_Details)
    Dialog_Details.show()
    sys.exit(app.exec_())
