from PyQt5 import QtCore, QtGui, QtWidgets
from dbmanager import DBManager, PrintManager
import os

class Ui_Dialog_Final(object):
    
    def setToday_1(self):
        self.dateEdit_1.setDate(QtCore.QDate.currentDate())
        
    def setToday_2(self):
        self.dateEdit_2.setDate(QtCore.QDate.currentDate())
        
    def search_details(self):
        self.date1 = self.dateEdit_1.date().toString('yyyy-MM-dd')
        self.date2 = self.dateEdit_2.date().toString('yyyy-MM-dd')
        self.name = self.cBox_name.currentText()
        
        self.tableWidget_1.clearContents()
        self.tableWidget_2.clearContents()
        self.tableWidget_1.setRowCount(1)
        
        self.dbManager.connect()
        
        self.query = "Select Name, replace(convert(varchar, convert(money, Dsales),1), '.00', ''), replace(convert(varchar, convert(money, DRefund),1), '.00', ''), replace(convert(varchar, convert(money, DCashin),1), '.00', ''), replace(convert(varchar, convert(money, DCardin),1), '.00', ''), replace(convert(varchar, convert(money, TTin),1), '.00', ''), replace(convert(varchar, convert(money, DBit),1), '.00', ''), replace(convert(varchar, convert(money, TBit),1), '.00', '') from (select Name, sum(Sales) as DSales, sum(Refund) as DRefund, sum(Cashin) as DCashin, sum(Cardin) as DCardin, sum(Cashin)+sum(Cardin) as TTin, sum(Sales)-sum(Cashin)-sum(Cardin)-sum(Refund) as DBit from Staff where Date between ? and ? and Name = ? group by Name) a, (select sum(Sales)-sum(Refund)-sum(Cashin)-sum(Cardin) as TBit from Staff where Date between '2019-01-01' and ? and Name = ?) b"
        self.dbManager.cursor.execute(self.query, (self.date1, self.date2, self.name, self.date2, self.name))
        self.rows = self.dbManager.cursor.fetchall()

        self.tbrow = 0
        for i in self.rows:
            item = QtWidgets.QTableWidgetItem(str(i[0]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_1.setItem(self.tbrow, 0, item)
            item = QtWidgets.QTableWidgetItem(str(i[1]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_1.setItem(self.tbrow, 1, item)
            item = QtWidgets.QTableWidgetItem(str(i[2]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_1.setItem(self.tbrow, 2, item)
            item = QtWidgets.QTableWidgetItem(str(i[3]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_1.setItem(self.tbrow, 3, item)
            item = QtWidgets.QTableWidgetItem(str(i[4]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_1.setItem(self.tbrow, 4, item)
            item = QtWidgets.QTableWidgetItem(str(i[5]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_1.setItem(self.tbrow, 5, item)
            item = QtWidgets.QTableWidgetItem(str(i[6]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_1.setItem(self.tbrow, 6, item)
            item = QtWidgets.QTableWidgetItem(str(i[7]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_1.setItem(self.tbrow, 7, item)
            self.tbrow += 1
        
        self.query = "Select Product, sum(Pout) from store where Date between ? and ? and Etcc = ? group by Product ORDER by Product ASC"
        self.dbManager.cursor.execute(self.query, (self.date1, self.date2, self.name))
        self.rows = self.dbManager.cursor.fetchall()
        self.tableWidget_2.setRowCount(len(self.rows))
        
        self.tbrow = 0
        for i in self.rows:
            item = QtWidgets.QTableWidgetItem(str(i[0]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_2.setItem(self.tbrow, 0, item)
            item = QtWidgets.QTableWidgetItem(str(i[1]))
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_2.setItem(self.tbrow, 1, item)
            self.tbrow += 1
        
        self.dbManager.close()
    
    def pprint_1(self):
        self.date1 = self.dateEdit_1.date().toString('yyyy-MM-dd')
        self.date2 = self.dateEdit_2.date().toString('yyyy-MM-dd')
        self.name = self.cBox_name.currentText()
        self.printManager.setprinter()
        self.directory = "C:/samusil/"
        self.file_name = self.directory + "check.txt"
        try:
            s0 = self.tableWidget_1.item(0, 0).text()
            s1 = self.tableWidget_1.item(0, 1).text()
            s2 = self.tableWidget_1.item(0, 2).text()
            s3 = self.tableWidget_1.item(0, 3).text()
            s4 = self.tableWidget_1.item(0, 4).text()
            s5 = self.tableWidget_1.item(0, 5).text()
            s6 = self.tableWidget_1.item(0, 6).text()
            s7 = self.tableWidget_1.item(0, 7).text()
        except:
            return
        
        f = open(self.file_name, 'w')
        f.write("\t기간:  "+self.date1+"  ~  "+self.date2+"\n")
        f.write("\t------------------------------------------------------------------\n\n")
        
        f.write("\t이름: "+s0+"\n\n\t기간매출: "+s1+"\n\n\t기간환불: "+
                s2+"\n\n\t기간현금입금: "+s3+"\n\n\t기간카드입금: "+
                s4+"\n\n\t총 입금 합계: "+s5+
                "\n\n\t기간미수: "+s6+"\n\n\t누적미수: "+s7+"\n\n")
        f.write("\t------------------------------------------------------------------\n\n")
        f.write("\t본인 확인:       "+self.name+"        (서명)\n\n")
        os.startfile(self.file_name, "print")
        f.close()
        
    
    def pprint_2(self):
        if self.tableWidget_2.item(0, 0) == None:
            return
        self.date1 = self.dateEdit_1.date().toString('yyyy-MM-dd')
        self.date2 = self.dateEdit_2.date().toString('yyyy-MM-dd')
        self.name = self.cBox_name.currentText()
        self.printManager.setprinter()
        self.directory = "C:/samusil/"
        self.file_name = self.directory + "check.txt"
        
        f = open(self.file_name, 'w')
        f.write("\t이름: "+self.name +"\t기간:  "+self.date1+"  ~  "+self.date2+"\n")
        f.write("\t------------------------------------------------------------------\n")
        for row in range(self.tableWidget_2.rowCount()):
            s0 = self.tableWidget_2.item(row, 0).text()
            s1 = self.tableWidget_2.item(row, 1).text()
            f.write("\t출고수량: {0}".format(s1)+"\t"+s0+"\n")
        f.write("\t------------------------------------------------------------------")
        os.startfile(self.file_name, "print")
        f.close()
    
    def setupUi(self, Dialog_Final):
        Dialog_Final.setObjectName("Dialog_Final")
        Dialog_Final.resize(1239, 847)
        self.tableWidget_1 = QtWidgets.QTableWidget(Dialog_Final)
        self.tableWidget_1.setGeometry(QtCore.QRect(10, 10, 921, 181))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_1.setFont(font)
        self.tableWidget_1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_1.setDragDropOverwriteMode(False)
        self.tableWidget_1.setAlternatingRowColors(True)
        self.tableWidget_1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_1.setShowGrid(True)
        self.tableWidget_1.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_1.setColumnCount(8)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(7, item)
        self.tableWidget_1.horizontalHeader().setVisible(True)
        self.tableWidget_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_1.verticalHeader().setVisible(False)
        self.tableWidget_1.setColumnWidth(0, 90)
        self.tableWidget_1.setColumnWidth(1, 120)
        self.tableWidget_1.setColumnWidth(3, 110)
        self.tableWidget_1.setColumnWidth(4, 110)
        self.tableWidget_1.setColumnWidth(5, 120)
        self.tableWidget_1.setColumnWidth(6, 130)
        self.tableWidget_1.setColumnWidth(7, 130)
        self.dbManager = DBManager()
        self.printManager = PrintManager()
        self.btn_print_1 = QtWidgets.QPushButton(Dialog_Final, clicked = self.pprint_1)
        self.btn_print_1.setGeometry(QtCore.QRect(740, 250, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_print_1.setFont(font)
        self.btn_print_1.setAutoDefault(False)
        self.btn_print_1.setDefault(False)
        self.btn_print_1.setFlat(False)
        self.btn_print_1.setObjectName("btn_print_1")
        self.label_11 = QtWidgets.QLabel(Dialog_Final)
        self.label_11.setGeometry(QtCore.QRect(190, 269, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.dateEdit_2 = QtWidgets.QDateEdit(Dialog_Final)
        self.dateEdit_2.setGeometry(QtCore.QRect(240, 260, 121, 41))
        self.dateEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setReadOnly(False)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.btn_search = QtWidgets.QPushButton(Dialog_Final, clicked = self.search_details)
        self.btn_search.setGeometry(QtCore.QRect(590, 250, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setAutoDefault(False)
        self.btn_search.setDefault(False)
        self.btn_search.setFlat(False)
        self.btn_search.setObjectName("btn_search")
        self.cBox_name = QtWidgets.QComboBox(Dialog_Final)
        self.cBox_name.setGeometry(QtCore.QRect(410, 264, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_name.setFont(font)
        self.cBox_name.setEditable(False)
        self.cBox_name.setModelColumn(0)
        self.cBox_name.setObjectName("cBox_name")
        self.dateEdit_1 = QtWidgets.QDateEdit(Dialog_Final)
        self.dateEdit_1.setGeometry(QtCore.QRect(60, 260, 121, 41))
        self.dateEdit_1.setFocusPolicy(QtCore.Qt.NoFocus)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_1.setFont(font)
        self.dateEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_1.setReadOnly(False)
        self.dateEdit_1.setCalendarPopup(True)
        self.dateEdit_1.setObjectName("dateEdit_1")
        
        self.dateEdit_1.setDate(QtCore.QDate.currentDate())
        self.dateEdit_2.setDate(QtCore.QDate.currentDate())
        self._today_button_1 = QtWidgets.QPushButton('&오늘', clicked=self.setToday_1)
        self.dateEdit_1.calendarWidget().layout().addWidget(self._today_button_1)
        self._today_button_2 = QtWidgets.QPushButton('&오늘', clicked=self.setToday_2)
        self.dateEdit_2.calendarWidget().layout().addWidget(self._today_button_2)
        
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog_Final)
        self.tableWidget_2.setGeometry(QtCore.QRect(930, 190, 301, 651))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setDragDropOverwriteMode(False)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.setColumnWidth(0, 235)
        self.tableWidget_2.setColumnWidth(1, 60)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(8)
        self.btn_print_2 = QtWidgets.QPushButton(Dialog_Final, clicked = self.pprint_2)
        self.btn_print_2.setGeometry(QtCore.QRect(780, 740, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_print_2.setFont(font)
        self.btn_print_2.setAutoDefault(False)
        self.btn_print_2.setDefault(False)
        self.btn_print_2.setFlat(False)
        self.btn_print_2.setObjectName("btn_print_2")
        
        self.dateEdit_1.wheelEvent = lambda event: None
        self.dateEdit_2.wheelEvent = lambda event: None
        self.cBox_name.wheelEvent = lambda event: None

        self.retranslateUi(Dialog_Final)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Final)

    def retranslateUi(self, Dialog_Final):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Final.setWindowTitle(_translate("Dialog_Final", "Dialog"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Final", "이름"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Final", "매출"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_Final", "환불"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_Final", "현금입금"))
        item = self.tableWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_Final", "카드입금"))
        item = self.tableWidget_1.horizontalHeaderItem(5)
        item.setText(_translate("Dialog_Final", "총입금합계"))
        item = self.tableWidget_1.horizontalHeaderItem(6)
        item.setText(_translate("Dialog_Final", "기간미수"))
        item = self.tableWidget_1.horizontalHeaderItem(7)
        item.setText(_translate("Dialog_Final", "누적미수"))
        self.btn_print_1.setText(_translate("Dialog_Final", "프린트"))
        self.label_11.setText(_translate("Dialog_Final", "~"))
        self.btn_search.setText(_translate("Dialog_Final", "조회"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Final", "제품명"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Final", "출고"))
        self.btn_print_2.setText(_translate("Dialog_Final", "프린트"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Final = QtWidgets.QDialog()
    ui = Ui_Dialog_Final()
    ui.setupUi(Dialog_Final)
    Dialog_Final.show()
    sys.exit(app.exec_())
