from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from dbmanager import DBManager, PrintManager
import os

class Ui_Dialog_Management(object):
    
    def setToday(self):
        self.dateEdit.setDate(QtCore.QDate.currentDate())
    
    def del_product(self):
        try:
            self.product = self.lineEdit_etc.text()
            if self.product == "":
                msg = QMessageBox()
                msg.setWindowTitle("오류")
                msg.setText("제품 이름을 입력하세요")
                msg.setIcon(QMessageBox.Critical)
                x = msg.exec()
            else:
                self.tableWidget_1.clearContents()
                self.tableWidget_2.clearContents()
                self.tableWidget_3.clearContents()
                self.tableWidget_4.clearContents()
                self.tableWidget_5.clearContents()
                self.dbManager.connect()
                self.query = "delete from store where Product = ?"
                self.dbManager.cursor.execute(self.query, (self.product))
                self.dbManager.conn.commit()
                self.dbManager.close()
                self.lineEdit_etc.setText("")
                msg = QMessageBox()
                msg.setWindowTitle("삭제완료")
                msg.setText("삭제 되었습니다.")
                msg.setIcon(QMessageBox.Information)
                x = msg.exec()
        except:
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품 이름을 정확히 입력하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
    
    def to_enable(self):
        if self.checkBox.isChecked():
            self.btn_delete.setEnabled(True)
            self.lineEdit_etc.setEnabled(True)
        else:
            self.btn_delete.setEnabled(False)
            self.lineEdit_etc.setEnabled(False)
    
    def search_details(self):
        self.tableWidget_1.clearContents()
        self.tableWidget_2.clearContents()
        self.tableWidget_3.clearContents()
        self.tableWidget_4.clearContents()
        self.tableWidget_5.clearContents()
        self.tableWidget_1.setRowCount(30)
        self.tableWidget_2.setRowCount(30)
        self.tableWidget_3.setRowCount(30)
        self.tableWidget_4.setRowCount(30)
        self.tableWidget_5.setRowCount(30)
        
        self.dbManager.connect()
        
        self.rows = self.dbManager.cursor.execute("select Product, sum(Pin)-sum(Pout) as 현재재고 from store group by Product ORDER by Product ASC")
        self.cnt = 0
        for i in self.rows:
            self.cnt += 1
        if self.cnt > 150:
            self.tableWidget_5.setRowCount(self.cnt-120)
        else:
            self.tableWidget_5.setRowCount(30)

        self.rows = self.dbManager.cursor.execute("select Product, sum(Pin)-sum(Pout) as 현재재고 from store group by Product ORDER by Product ASC")
        self.tbrow = 0
        for i in self.rows:
            if self.tbrow < 30:
                item = QtWidgets.QTableWidgetItem(str(i[0]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_1.setItem(self.tbrow, 0, item)
                item = QtWidgets.QTableWidgetItem(str(i[1]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_1.setItem(self.tbrow, 1, item)
            elif self.tbrow < 60:
                item = QtWidgets.QTableWidgetItem(str(i[0]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_2.setItem(self.tbrow-30, 0, item)
                item = QtWidgets.QTableWidgetItem(str(i[1]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_2.setItem(self.tbrow-30, 1, item)
            elif self.tbrow < 90:
                item = QtWidgets.QTableWidgetItem(str(i[0]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_3.setItem(self.tbrow-60, 0, item)
                item = QtWidgets.QTableWidgetItem(str(i[1]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_3.setItem(self.tbrow-60, 1, item)
            elif self.tbrow < 120:
                item = QtWidgets.QTableWidgetItem(str(i[0]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_4.setItem(self.tbrow-90, 0, item)
                item = QtWidgets.QTableWidgetItem(str(i[1]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_4.setItem(self.tbrow-90, 1, item)
            else:
                item = QtWidgets.QTableWidgetItem(str(i[0]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_5.setItem(self.tbrow-120, 0, item)
                item = QtWidgets.QTableWidgetItem(str(i[1]))
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_5.setItem(self.tbrow-120, 1, item)
            
            self.tbrow += 1

        self.dbManager.close()
        
    def insert_product(self):
        if self.cBox_product_1.currentText() == "" and self.cBox_product_2.currentText() == "" and self.cBox_product_3.currentText() == "":
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품을 선택하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        elif self.cBox_product_1.currentText() != "" and self.sBox_pin_1.value() == 0 and self.sBox_pout_1.value() == 0:
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품 개수를 확인하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        elif self.cBox_product_2.currentText() != "" and self.sBox_pin_2.value() == 0 and self.sBox_pout_2.value() == 0:
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품 개수를 확인하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        elif self.cBox_product_3.currentText() != "" and self.sBox_pin_3.value() == 0 and self.sBox_pout_3.value() == 0:
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품 개수를 확인하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        else:
            self.date = self.dateEdit.date().toString('yyyy-MM-dd')
            self.name = self.cBox_name.currentText()
            self.tableWidget_1.clearContents()
            self.tableWidget_2.clearContents()
            self.tableWidget_3.clearContents()
            self.tableWidget_4.clearContents()
            self.tableWidget_5.clearContents()
            self.dbManager.connect()
            
            for i in range(0, 3):
                if self.cboxs[i].currentText() != "":
                    self.product = self.cboxs[i].currentText()
                    self.pin = self.sboxs_in[i].value()
                    self.pout = self.sboxs_out[i].value()
                
                    self.query = "Insert into store (Date, Product, Pin, Pout, Etcc) VALUES(?,?,?,?,?)"
                    self.dbManager.cursor.execute(self.query, (self.date, self.product, self.pin, self.pout, self.name))
                    self.dbManager.conn.commit()
            
            self.dbManager.close()
            self.search_details()
            msg = QMessageBox()
            msg.setWindowTitle("입력완료")
            msg.setText("입력 되었습니다")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec()
            self.cBox_name.setCurrentIndex(0)
            self.cBox_product_1.setCurrentIndex(0)
            self.cBox_product_2.setCurrentIndex(0)
            self.cBox_product_3.setCurrentIndex(0)
            self.sBox_pin_1.setValue(0)
            self.sBox_pin_2.setValue(0)
            self.sBox_pin_3.setValue(0)
            self.sBox_pout_1.setValue(0)
            self.sBox_pout_2.setValue(0)
            self.sBox_pout_3.setValue(0)

    def pprint(self):
        if self.tableWidget_1.item(0, 0) == None:
            return
        self.printManager.setprinter()
        self.directory = "C:/samusil/"
        self.file_name = self.directory + "cstore.txt"
        f = open(self.file_name, 'w')
        for row in range(self.tableWidget_1.rowCount()):
            if self.tableWidget_1.item(row, 0) == None:
                pass
            else:
                s0 = self.tableWidget_1.item(row, 0).text()
                s1 = self.tableWidget_1.item(row, 1).text()
                f.write("재고 수량: "+s1+"\t"+s0+"\n")
            
        for row in range(self.tableWidget_2.rowCount()):
            if self.tableWidget_2.item(row, 0) == None:
                pass
            else:
                s0 = self.tableWidget_2.item(row, 0).text()
                s1 = self.tableWidget_2.item(row, 1).text()
                f.write("재고 수량: "+s1+"\t"+s0+"\n")
        for row in range(self.tableWidget_3.rowCount()):
            if self.tableWidget_3.item(row, 0) == None:
                pass
            else:
                s0 = self.tableWidget_3.item(row, 0).text()
                s1 = self.tableWidget_3.item(row, 1).text()
                f.write("재고 수량: "+s1+"\t"+s0+"\n")
        for row in range(self.tableWidget_4.rowCount()):
            if self.tableWidget_4.item(row, 0) == None:
                pass
            else:
                s0 = self.tableWidget_4.item(row, 0).text()
                s1 = self.tableWidget_4.item(row, 1).text()
                f.write("재고 수량: "+s1+"\t"+s0+"\n")
        for row in range(self.tableWidget_5.rowCount()):
            if self.tableWidget_5.item(row, 0) == None:
                pass
            else:
                s0 = self.tableWidget_5.item(row, 0).text()
                s1 = self.tableWidget_5.item(row, 1).text()
                f.write("재고 수량: "+s1+"\t"+s0+"\n")
        os.startfile(self.file_name, "print")
        f.close()
            

    def setupUi(self, Dialog_Management):
        Dialog_Management.setObjectName("Dialog_Management")
        Dialog_Management.resize(1641, 888)
        self.dateEdit = QtWidgets.QDateEdit(Dialog_Management)
        self.dateEdit.setGeometry(QtCore.QRect(30, 55, 121, 41))
        self.dateEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self._today_button = QtWidgets.QPushButton('&오늘', clicked=self.setToday)
        self.dateEdit.calendarWidget().layout().addWidget(self._today_button)
        self.dateEdit.wheelEvent = lambda event: None
        self.dbManager = DBManager()
        self.printManager = PrintManager()
        self.sBox_pout_3 = QtWidgets.QSpinBox(Dialog_Management)
        self.sBox_pout_3.setGeometry(QtCore.QRect(710, 90, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_pout_3.setFont(font)
        self.sBox_pout_3.setMaximum(999)
        self.sBox_pout_3.setObjectName("sBox_pout_3")
        self.sBox_pout_1 = QtWidgets.QSpinBox(Dialog_Management)
        self.sBox_pout_1.setGeometry(QtCore.QRect(710, 20, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_pout_1.setFont(font)
        self.sBox_pout_1.setMaximum(999)
        self.sBox_pout_1.setObjectName("sBox_pout_1")
        self.sBox_pin_3 = QtWidgets.QSpinBox(Dialog_Management)
        self.sBox_pin_3.setGeometry(QtCore.QRect(600, 90, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_pin_3.setFont(font)
        self.sBox_pin_3.setMaximum(999)
        self.sBox_pin_3.setObjectName("sBox_pin_3")
        self.cBox_product_2 = QtWidgets.QComboBox(Dialog_Management)
        self.cBox_product_2.setGeometry(QtCore.QRect(180, 55, 361, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_2.setFont(font)
        self.cBox_product_2.setObjectName("cBox_product_2")
        self.cBox_product_3 = QtWidgets.QComboBox(Dialog_Management)
        self.cBox_product_3.setGeometry(QtCore.QRect(180, 90, 361, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_3.setFont(font)
        self.cBox_product_3.setObjectName("cBox_product_3")
        self.sBox_pin_1 = QtWidgets.QSpinBox(Dialog_Management)
        self.sBox_pin_1.setGeometry(QtCore.QRect(600, 20, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_pin_1.setFont(font)
        self.sBox_pin_1.setMaximum(999)
        self.sBox_pin_1.setObjectName("sBox_pin_1")
        self.sBox_pin_2 = QtWidgets.QSpinBox(Dialog_Management)
        self.sBox_pin_2.setGeometry(QtCore.QRect(600, 55, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_pin_2.setFont(font)
        self.sBox_pin_2.setMaximum(999)
        self.sBox_pin_2.setObjectName("sBox_pin_2")
        self.cBox_product_1 = QtWidgets.QComboBox(Dialog_Management)
        self.cBox_product_1.setGeometry(QtCore.QRect(180, 20, 361, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_1.setFont(font)
        self.cBox_product_1.setObjectName("cBox_product_1")
        self.sBox_pout_2 = QtWidgets.QSpinBox(Dialog_Management)
        self.sBox_pout_2.setGeometry(QtCore.QRect(710, 55, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_pout_2.setFont(font)
        self.sBox_pout_2.setMaximum(999)
        self.sBox_pout_2.setObjectName("sBox_pout_2")
        self.btn_insert = QtWidgets.QPushButton(Dialog_Management, clicked = self.insert_product)
        self.btn_insert.setGeometry(QtCore.QRect(980, 42, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_insert.setFont(font)
        self.btn_insert.setAutoDefault(False)
        self.btn_insert.setDefault(False)
        self.btn_insert.setFlat(False)
        self.btn_insert.setObjectName("btn_insert")
        
        self.checkBox = QtWidgets.QCheckBox(Dialog_Management, stateChanged = self.to_enable)
        self.checkBox.setGeometry(QtCore.QRect(1600, 10, 51, 31))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        
        self.btn_delete = QtWidgets.QPushButton(Dialog_Management, clicked = self.del_product)
        self.btn_delete.setGeometry(QtCore.QRect(1500, 52, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setEnabled(False)
        self.btn_delete.setAutoDefault(False)
        self.btn_delete.setDefault(False)
        self.btn_delete.setFlat(False)
        self.btn_delete.setObjectName("btn_delete")
        
        self.lineEdit_etc = QtWidgets.QLineEdit(Dialog_Management)
        self.lineEdit_etc.setGeometry(QtCore.QRect(1300, 55, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc.setFont(font)
        self.lineEdit_etc.setEnabled(False)
        self.lineEdit_etc.setObjectName("lineEdit_etc")
        
        self.cBox_name = QtWidgets.QComboBox(Dialog_Management)
        self.cBox_name.setGeometry(QtCore.QRect(810, 55, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_name.setFont(font)
        self.cBox_name.setEditable(True)
        self.cBox_name.setObjectName("cBox_name")
        self.label_2 = QtWidgets.QLabel(Dialog_Management)
        self.label_2.setGeometry(QtCore.QRect(550, 20, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_Management)
        self.label_3.setGeometry(QtCore.QRect(550, 55, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog_Management)
        self.label_4.setGeometry(QtCore.QRect(550, 90, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog_Management)
        self.label_5.setGeometry(QtCore.QRect(660, 20, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog_Management)
        self.label_6.setGeometry(QtCore.QRect(660, 55, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog_Management)
        self.label_7.setGeometry(QtCore.QRect(660, 90, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btn_search = QtWidgets.QPushButton(Dialog_Management, clicked = self.search_details)
        self.btn_search.setGeometry(QtCore.QRect(30, 450, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setAutoDefault(False)
        self.btn_search.setDefault(False)
        self.btn_search.setFlat(False)
        self.btn_search.setObjectName("btn_search")
        self.btn_print = QtWidgets.QPushButton(Dialog_Management, clicked = self.pprint)
        self.btn_print.setGeometry(QtCore.QRect(37, 650, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_print.setFont(font)
        self.btn_print.setAutoDefault(False)
        self.btn_print.setDefault(False)
        self.btn_print.setFlat(False)
        self.btn_print.setObjectName("btn_print")
        self.tableWidget_1 = QtWidgets.QTableWidget(Dialog_Management)
        self.tableWidget_1.setGeometry(QtCore.QRect(140, 130, 291, 750))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_1.setFont(font)
        self.tableWidget_1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_1.setDragDropOverwriteMode(False)
        self.tableWidget_1.setAlternatingRowColors(True)
        self.tableWidget_1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_1.setShowGrid(True)
        self.tableWidget_1.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_1.setColumnCount(2)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        self.tableWidget_1.horizontalHeader().setVisible(True)
        self.tableWidget_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_1.verticalHeader().setVisible(False)
        self.tableWidget_1.setColumnWidth(0, 205)
        self.tableWidget_1.setColumnWidth(1, 80)
        self.tableWidget_1.verticalHeader().setDefaultSectionSize(8)
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog_Management)
        self.tableWidget_2.setGeometry(QtCore.QRect(440, 130, 291, 750))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setDragDropOverwriteMode(False)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.setColumnWidth(0, 205)
        self.tableWidget_2.setColumnWidth(1, 80)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(8)
        self.tableWidget_3 = QtWidgets.QTableWidget(Dialog_Management)
        self.tableWidget_3.setGeometry(QtCore.QRect(740, 130, 291, 750))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setDragDropOverwriteMode(False)
        self.tableWidget_3.setAlternatingRowColors(True)
        self.tableWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.tableWidget_3.horizontalHeader().setVisible(True)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.setColumnWidth(0, 205)
        self.tableWidget_3.setColumnWidth(1, 80)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(8)
        self.tableWidget_4 = QtWidgets.QTableWidget(Dialog_Management)
        self.tableWidget_4.setGeometry(QtCore.QRect(1040, 130, 291, 750))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setDragDropOverwriteMode(False)
        self.tableWidget_4.setAlternatingRowColors(True)
        self.tableWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setShowGrid(True)
        self.tableWidget_4.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.tableWidget_4.horizontalHeader().setVisible(True)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.tableWidget_4.setColumnWidth(0, 205)
        self.tableWidget_4.setColumnWidth(1, 80)
        self.tableWidget_4.verticalHeader().setDefaultSectionSize(8)
        self.tableWidget_5 = QtWidgets.QTableWidget(Dialog_Management)
        self.tableWidget_5.setGeometry(QtCore.QRect(1340, 130, 291, 750))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_5.setDragDropOverwriteMode(False)
        self.tableWidget_5.setAlternatingRowColors(True)
        self.tableWidget_5.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_5.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_5.setShowGrid(True)
        self.tableWidget_5.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_5.setColumnCount(2)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        self.tableWidget_5.horizontalHeader().setVisible(True)
        self.tableWidget_5.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.tableWidget_5.setColumnWidth(0, 205)
        self.tableWidget_5.setColumnWidth(1, 80)
        self.tableWidget_5.verticalHeader().setDefaultSectionSize(8)
        
        self.cboxs = [self.cBox_product_1, self.cBox_product_2, self.cBox_product_3]
        self.sboxs_in = [self.sBox_pin_1, self.sBox_pin_2, self.sBox_pin_3]
        self.sboxs_out = [self.sBox_pout_1, self.sBox_pout_2, self.sBox_pout_3]
        
        self.sBox_pin_1.wheelEvent = lambda event: None
        self.sBox_pin_2.wheelEvent = lambda event: None
        self.sBox_pin_3.wheelEvent = lambda event: None
        self.sBox_pout_1.wheelEvent = lambda event: None
        self.sBox_pout_2.wheelEvent = lambda event: None
        self.sBox_pout_3.wheelEvent = lambda event: None
        self.cBox_name.wheelEvent = lambda event: None
        self.cBox_product_1.wheelEvent = lambda event: None
        self.cBox_product_2.wheelEvent = lambda event: None
        self.cBox_product_3.wheelEvent = lambda event: None

        self.retranslateUi(Dialog_Management)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Management)

    def retranslateUi(self, Dialog_Management):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Management.setWindowTitle(_translate("Dialog_Management", "Dialog"))
        self.btn_insert.setText(_translate("Dialog_Management", "입력"))
        self.btn_delete.setText(_translate("Dialog_Management", "삭제"))
        self.label_2.setText(_translate("Dialog_Management", "입고:"))
        self.label_3.setText(_translate("Dialog_Management", "입고:"))
        self.label_4.setText(_translate("Dialog_Management", "입고:"))
        self.label_5.setText(_translate("Dialog_Management", "출고:"))
        self.label_6.setText(_translate("Dialog_Management", "출고:"))
        self.label_7.setText(_translate("Dialog_Management", "출고:"))
        self.btn_search.setText(_translate("Dialog_Management", "재고조회"))
        self.btn_print.setText(_translate("Dialog_Management", "프린트"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Management", "제품명"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Management", "재고수량"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Management", "제품명"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Management", "재고수량"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Management", "제품명"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Management", "재고수량"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Management", "제품명"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Management", "재고수량"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Management", "제품명"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Management", "재고수량"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Management = QtWidgets.QDialog()
    ui = Ui_Dialog_Management()
    ui.setupUi(Dialog_Management)
    Dialog_Management.show()
    sys.exit(app.exec_())
