from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from dialog_details import Ui_Dialog_Details
from dialog_add import Ui_Dialog_Add
from dialog_card_details import Ui_Dialog_Card_Details
from dialog_final import Ui_Dialog_Final
from dialog_management import Ui_Dialog_Management
from dialog_product_details import Ui_Dialog_Product_Detils
from dialog_branch import Ui_Dialog_Branch
from dialog_branch_details import Ui_Dialog_Branch_Details
from dialog_bonsa import Ui_Dialog_Bonsa
from dialog_bonsa_details import Ui_Dialog_Bonsa_Details
from dialog_deposit import Ui_Dialog_Deposit
from dialog_payslip import Ui_Dialog_Payslip
from filemanager import FileManager
from dbmanager import DBManager
import datetime


class Ui_MainWindow(object):

    def open_payslip(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Payslip()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.setMaxVisibleItems(22)

    def open_deposit(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Deposit()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.setMaxVisibleItems(22)
        self.ui.cBox_name.wheelEvent = lambda event: None
        self.ui.sBox_deposit.wheelEvent = lambda event: None
        self.ui.label_info.setText(f"* 적금 횟수는 {datetime.datetime.today().year}년 {datetime.datetime.today().month}월 기준 횟수로 입력")
    
    def open_bonsa(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Bonsa()
        self.ui.setupUi(self.window)
        self.window.show()
        for i in self.ui.cboxs:
            i.addItems(['']+self.fManager.items)
            i.setMaxVisibleItems(35)
            i.setCurrentIndex(0)
        for i in self.ui.percents:
            i.addItems(self.fManager.bonsa_percent)
            i.setCurrentIndex(0)
        
    def open_bonsa_details(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Bonsa_Details()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.addItems(['전체', '생앤', '백옥생'])
        self.ui.cBox_name.setCurrentIndex(0)
    
    def open_branch(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Branch()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.addItems(self.fManager.branch_names)
        self.ui.cBox_name.setMaxVisibleItems(22)
        self.ui.cBox_name.setCurrentIndex(-1)
        for i in self.ui.cboxs:
            i.addItems(['']+self.fManager.items)
            i.setMaxVisibleItems(35)
            i.setCurrentIndex(0)
        for i in self.ui.percents:
            i.addItems(self.fManager.branch_percent)
            i.setCurrentIndex(0)
        
    def open_branch_details(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Branch_Details()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.addItems(['전체']+self.fManager.branch_names)
        self.ui.cBox_name.setCurrentIndex(0)
        self.ui.cBox_name.setMaxVisibleItems(22)
    
    def open_details(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Details()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.addItems(['전체']+self.fManager.names)
        self.ui.cBox_name.setMaxVisibleItems(22)
    
    def open_add(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Add()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_product.clear()
        self.ui.cBox_product.addItems(self.fManager.items)
        self.ui.cBox_product.setMaxVisibleItems(35)
        self.ui.cBox_product.setCurrentIndex(-1)
        self.ui.btn_insert.clicked.connect(self.add_item)
        self.ui.btn_delete.clicked.connect(self.del_item)
        self.ui.btn_update.clicked.connect(self.update_item)
        
    def add_item(self):
        self.product = self.ui.lineEdit_product.text()
        if self.ui.lineEdit_price.text() == "":
            self.price = "0"
        else:
            self.price = self.ui.lineEdit_price.text().replace(',','')
        if self.product == "" or self.price == "":
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("추가할 제품이나 금액을 적어주세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        else:
            self.dbManager.connect()
            self.query = "Insert into productinfo (product, price) VALUES(?,?)"
            self.dbManager.cursor.execute(self.query, (self.product, self.price))
            self.dbManager.conn.commit()
            self.fManager.items.append(self.product)
            self.fManager.items.sort()
            self.fManager.save()
            self.dbManager.close()
            self.ui.lineEdit_product.setText("")
            self.ui.lineEdit_price.setText("")
            self.load_list()
            self.ui.cBox_product.clear()
            self.ui.cBox_product.addItems(self.fManager.items)
            self.ui.cBox_product.setCurrentIndex(-1)
            msg = QMessageBox()
            msg.setWindowTitle("추가완료")
            msg.setText("추가 되었습니다.")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec()
  
    def del_item(self):
        self.product = self.ui.cBox_product.currentText()
        if self.product not in self.fManager.items:
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("삭제할 제품명을 정확히 적어주세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        else:
            self.dbManager.connect()
            self.query = "delete from productinfo where product = ?"
            self.dbManager.cursor.execute(self.query, (self.product))
            self.dbManager.conn.commit()
            self.fManager.items.remove(self.product)
            self.fManager.save()
            self.dbManager.close()
            self.load_list()
            self.ui.cBox_product.clear()
            self.ui.cBox_product.addItems(self.fManager.items)
            self.ui.cBox_product.setCurrentIndex(-1)
            msg = QMessageBox()
            msg.setWindowTitle("삭제완료")
            msg.setText("삭제 되었습니다.")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec()
    
    def update_item(self):
        self.prename = self.ui.lineEdit_update_1.text()
        self.updatename = self.ui.lineEdit_update_2.text()
        if self.prename == "" or self.updatename == "":
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품명을 적어주세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        else:
            self.dbManager.connect()
            self.query = "UPDATE store SET Product = ? WHERE Product = ?"
            self.dbManager.cursor.execute(self.query, (self.updatename, self.prename))
            self.dbManager.conn.commit()

            self.query = "UPDATE productinfo SET product = ? WHERE product = ?"
            self.dbManager.cursor.execute(self.query, (self.updatename, self.prename))
            self.dbManager.conn.commit()

            self.dbManager.close()
            self.ui.lineEdit_update_1.setText("")
            self.ui.lineEdit_update_2.setText("")
            try:
                self.fManager.items.remove(self.prename)
                self.fManager.items.append(self.updatename)
                self.fManager.items.sort()
                self.fManager.save()
                self.load_list()
                self.ui.cBox_product.clear()
                self.ui.cBox_product.addItems(self.fManager.items)
                self.ui.cBox_product.setCurrentIndex(-1)
            except:
                print("file replace error")
            msg = QMessageBox()
            msg.setWindowTitle("변경완료")
            msg.setText("변경 되었습니다.")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec()
    
    def open_card_details(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Card_Details()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def open_final(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Final()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.addItems(self.fManager.names)
        self.ui.cBox_name.setMaxVisibleItems(22)
        self.ui.cBox_name.setCurrentIndex(1)
        
    def open_management(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Management()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.addItems(["정리"]+self.fManager.management_names+self.fManager.names)
        self.ui.cBox_name.setMaxVisibleItems(22)
        self.ui.cBox_name.setCurrentIndex(0)
        self.ui.cBox_product_1.addItems([""]+self.fManager.items + self.fManager.management_items)
        self.ui.cBox_product_1.setMaxVisibleItems(35)
        self.ui.cBox_product_1.setCurrentIndex(0)
        self.ui.cBox_product_2.addItems([""]+self.fManager.items + self.fManager.management_items)
        self.ui.cBox_product_2.setMaxVisibleItems(35)
        self.ui.cBox_product_2.setCurrentIndex(0)
        self.ui.cBox_product_3.addItems([""]+self.fManager.items + self.fManager.management_items)
        self.ui.cBox_product_3.setMaxVisibleItems(35)
        self.ui.cBox_product_3.setCurrentIndex(0)
    
    def open_product_details(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Product_Detils()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.cBox_name.addItems(['전체', '정리']+self.fManager.management_names+self.fManager.names+self.fManager.branch_names)
        self.ui.cBox_name.setMaxVisibleItems(30)
        
    def reset(self):
        self.lineEdit_cardin.setText("0")
        self.lineEdit_cashin.setText("0")
        self.lineEdit_etc.setText("")
        self.lineEdit_number.setText("")
        self.lineEdit_refund.setText("0")
        self.lineEdit_sales.setText("0")
        self.cBox_name.setCurrentIndex(-1)
        self.cBox_cardkind.setCurrentIndex(-1)
        for i in self.cboxs:
            i.setCurrentIndex(-1)
        for i in self.sboxs:
            i.setValue(0)
        for i in self.sboxs_sv:
            i.setValue(0)
        self.dateEdit_main.calendarWidget().setSelectedDate(QtCore.QDate.currentDate())
        self.dateEdit_sub_1.calendarWidget().setSelectedDate(QtCore.QDate.currentDate())
        self.dateEdit_sub_2.calendarWidget().setSelectedDate(QtCore.QDate.currentDate())
        self.label_12.setText("총매출: ")
        self.label_13.setText("총입금: ")
        self.label_14.setText("현금입금: ")
        self.label_15.setText("카드입금: ")
        self.label_16.setText("반품처리: ")
        
    def load_list(self):
        self.maxvisibal = 25
        for cbox in self.cboxs:
            cbox.clear()
            cbox.addItems(self.fManager.items)
            cbox.setMaxVisibleItems(self.maxvisibal)
            cbox.setCurrentIndex(-1)

    def calc_sales(self, cb, sv1, sv2):
        if cb.currentText() != "" and sv1.value() != 0:
            self.pname = cb.currentText()
            self.query = "Select price from productinfo where product = ?"
            self.result = self.dbManager.cursor.execute(self.query, self.pname)
            for i in self.result:
                self.get_price = i[0]
            self.carc_price= (int(sv1.value())-int(sv2.value()))*self.get_price
            self.total_price.append(self.carc_price)
        else:
            self.total_price.append(0)
    
    def calc_Product(self):
        del self.total_price[:]
        self.dbManager.connect()
        for i in range(0, 10):
            self.calc_sales(self.cboxs[i], self.sboxs[i], self.sboxs_sv[i])
        self.lineEdit_sales.setText(format(sum(self.total_price), ','))
        self.dbManager.close()
    
    def check_cBox(self):
        for i in range(0, 10):
            if self.cboxs[i].currentText() != "" and self.sboxs[i].value() == 0:
                return True
            if self.cboxs[i].currentText() == "" and self.sboxs[i].value() != 0:
                return True
        return False
    
    def check_calc(self):
        for i in self.cboxs:
            if i.currentText() != "" and self.lineEdit_sales.text() == '0':
                return True
        return False
    
    def set_lineEdit(self):
        for i in self.lines:
            txt = i.text().replace(',','')
            if i.text() != "":
                i.setText(format(int(txt), ','))
            else:
                i.setText("0")
            
    def insert_Sales(self):
        if self.lineEdit_cardin.text() == "":
            self.lineEdit_cardin.setText("0")
        if self.lineEdit_cashin.text() == "":
             self.lineEdit_cashin.setText("0")
        if self.lineEdit_refund.text() == "":
            self.lineEdit_refund.setText("0")
        if self.lineEdit_sales.text() == "":
            self.lineEdit_sales.setText("0")
        
        if self.cBox_name.currentText() == "":
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("이름을 선택하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        elif self.check_cBox():
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("제품이나 제품 개수를 확인하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        elif self.check_calc():
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("계산 버튼을 클릭했는지 확인하세요")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        elif self.lineEdit_cardin.text() == "0" and self.lineEdit_cashin.text() == "0" and self.lineEdit_refund.text() == "0" and self.lineEdit_sales.text() == "0":
            msg = QMessageBox()
            msg.setWindowTitle("오류")
            msg.setText("아무 금액도 입력되지 않았습니다.")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec()
        else:
            self.date = self.dateEdit_main.date().toString('yyyy-MM-dd')
            self.name = self.cBox_name.currentText()
            self.sales = self.lineEdit_sales.text().replace(',','')
            self.refund = self.lineEdit_refund.text().replace(',','')
            self.cash_in = self.lineEdit_cashin.text().replace(',','')
            self.card_in = self.lineEdit_cardin.text().replace(',','')
            self.etc = self.lineEdit_etc.text()
            self.card_num = self.lineEdit_number.text()
            self.card_sa = self.cBox_cardkind.currentText()
            self.pin = '0'
            
            self.dbManager.connect()
            for i in range(0, 10):
                if self.cboxs[i].currentText() != "" and self.sboxs[i].value() != 0:
                    self.product = self.cboxs[i].currentText()
                    self.pout = str(self.sboxs[i].value())
                    self.query = "Insert into store (Date, Product, Pin, Pout, Etcc) VALUES(?,?,?,?,?)"
                    self.dbManager.cursor.execute(self.query, (self.date, self.product, self.pin, self.pout, self.name))
                    self.dbManager.conn.commit()

            self.query = "Insert into Staff (Date, Name, Sales, Refund, Cashin, Cardin, Etcc, Number, Cardkind) VALUES(?,?,?,?,?,?,?,?,?)"
            self.dbManager.cursor.execute(self.query, (self.date, self.name, self.sales, self.refund, self.cash_in, self.card_in, self.etc, self.card_num, self.card_sa))
            self.dbManager.conn.commit()
            
            self.dbManager.close()
            msg = QMessageBox()
            msg.setWindowTitle("입력완료")
            msg.setText("입력 되었습니다.")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec()
            
            
            self.reset()

    
    def wrapup(self):
        self.date1 = self.dateEdit_sub_1.date().toString('yyyy-MM-dd')
        self.date2 = self.dateEdit_sub_2.date().toString('yyyy-MM-dd')

        self.dbManager.connect()

        query = "Select sum(Sales) as TSales, sum(Refund)+sum(Cashin)+sum(Cardin) as Tin from Staff where Date between ? and ?"
        result = self.dbManager.cursor.execute(query, (self.date1, self.date2))
        for i in result:
            t_sale = i[0]
            t_in = i[1]
        if t_sale != None:
            t_sale = format(t_sale, ',')
        else:
            t_sale = 0
        if t_in != None:
            t_in = format(t_in, ',')
        else:
            t_in = 0
        self.label_12.setText(f"총매출:  {t_sale}")
        self.label_13.setText(f"총입금:  {t_in}")
        
        query =  "Select sum(Cardin) as TCard, sum(Cashin) as TCash, sum(Refund) as TRefund from Staff where Date between ? and ?"
        result = self.dbManager.cursor.execute(query, (self.date1, self.date2))
        for i in result:
            tCard = i[0]
            tCash = i[1]
            tRefund = i[2]
        if tCard != None:
            tCard = format(tCard, ',')
        else:
            tCard = 0
        if tCash != None:
            tCash = format(tCash, ',')
        else:
            tCash = 0
        if tRefund != None:
            tRefund = format(tRefund, ',')
        else:
            tRefund = 0

        
        self.label_14.setText(f"현금입금: {tCash}")
        self.label_15.setText(f"카드입금: {tCard}")
        self.label_16.setText(f"반품처리: {tRefund}")
        self.dbManager.close()

        
    def setToday(self):
        self.dateEdit_main.calendarWidget().setSelectedDate(QtCore.QDate.currentDate())
    def setToday_sub_1(self):
        self.dateEdit_sub_1.calendarWidget().setSelectedDate(QtCore.QDate.currentDate())
    def setToday_sub_2(self):
        self.dateEdit_sub_2.calendarWidget().setSelectedDate(QtCore.QDate.currentDate())
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1220, 870)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1220, 870))
        MainWindow.setMaximumSize(QtCore.QSize(1220, 870))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        
        self.fManager = FileManager()
        self.dbManager = DBManager()
        self.total_price = []
        
        self.today = QtCore.QDate.currentDate().toString(QtCore.Qt.DefaultLocaleLongDate)
        self.now = QtCore.QDate.currentDate().toString(QtCore.Qt.ISODate)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 80, 391, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dateEdit_main = QtWidgets.QDateEdit(self.frame)
        self.dateEdit_main.setGeometry(QtCore.QRect(30, 10, 121, 41))
        self.dateEdit_main.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateEdit_main.setDate(QtCore.QDate.currentDate())
        self.dateEdit_main.wheelEvent = lambda event: None
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_main.setFont(font)
        self.dateEdit_main.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_main.setReadOnly(False)
        self.dateEdit_main.setCalendarPopup(True)
        self.dateEdit_main.setObjectName("dateEdit_main")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(45, 83, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(31, 290, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(42, 340, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cBox_name = QtWidgets.QComboBox(self.frame)
        self.cBox_name.setGeometry(QtCore.QRect(130, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_name.setFont(font)
        self.cBox_name.setEditable(False)
        self.cBox_name.setModelColumn(0)
        self.cBox_name.setObjectName("cBox_name")
        self.cBox_name.addItems(self.fManager.names)
        self.cBox_name.setMaxVisibleItems(20)
        self.cBox_name.setCurrentIndex(-1)
        self.lineEdit_cashin = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_cashin.setGeometry(QtCore.QRect(120, 140, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_cashin.setFont(font)
        self.lineEdit_cashin.setObjectName("lineEdit_cashin")
        self.lineEdit_cardin = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_cardin.setGeometry(QtCore.QRect(120, 190, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_cardin.setFont(font)
        self.lineEdit_cardin.setObjectName("lineEdit_cardin")
        self.lineEdit_number = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_number.setGeometry(QtCore.QRect(120, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_number.setFont(font)
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.lineEdit_refund = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_refund.setGeometry(QtCore.QRect(120, 290, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_refund.setFont(font)
        self.lineEdit_refund.setObjectName("lineEdit_refund")
        self.lineEdit_etc = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_etc.setGeometry(QtCore.QRect(120, 340, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_etc.setFont(font)
        self.lineEdit_etc.setObjectName("lineEdit_etc")
        self.cBox_cardkind = QtWidgets.QComboBox(self.frame)
        self.cBox_cardkind.setGeometry(QtCore.QRect(300, 240, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_cardkind.setFont(font)
        self.cBox_cardkind.setObjectName("cBox_cardkind")
        
        self.cBox_cardkind.addItems(self.fManager.cardkind)
        self.cBox_cardkind.setMaxVisibleItems(15)
        self.cBox_cardkind.setCurrentIndex(-1)
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(410, 40, 921, 611))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_reset = QtWidgets.QPushButton(self.frame_2, clicked = self.reset)
        self.btn_reset.setGeometry(QtCore.QRect(100, 10, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_reset.setFont(font)
        self.btn_reset.setAutoDefault(False)
        self.btn_reset.setDefault(False)
        self.btn_reset.setFlat(False)
        self.btn_reset.setObjectName("btn_reset")

        self.cBox_product_1 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_1.setGeometry(QtCore.QRect(20, 110, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_1.setFont(font)
        self.cBox_product_1.setObjectName("cBox_product_1")
        self.cBox_product_2 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_2.setGeometry(QtCore.QRect(20, 160, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_2.setFont(font)
        self.cBox_product_2.setObjectName("cBox_product_2")
        self.cBox_product_3 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_3.setGeometry(QtCore.QRect(20, 210, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_3.setFont(font)
        self.cBox_product_3.setObjectName("cBox_product_3")
        self.cBox_product_4 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_4.setGeometry(QtCore.QRect(20, 260, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_4.setFont(font)
        self.cBox_product_4.setObjectName("cBox_product_4")
        self.cBox_product_5 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_5.setGeometry(QtCore.QRect(20, 310, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_5.setFont(font)
        self.cBox_product_5.setObjectName("cBox_product_5")
        self.cBox_product_6 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_6.setGeometry(QtCore.QRect(20, 360, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_6.setFont(font)
        self.cBox_product_6.setObjectName("cBox_product_6")
        self.cBox_product_7 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_7.setGeometry(QtCore.QRect(20, 410, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_7.setFont(font)
        self.cBox_product_7.setObjectName("cBox_product_7")
        self.cBox_product_8 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_8.setGeometry(QtCore.QRect(20, 460, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_8.setFont(font)
        self.cBox_product_8.setObjectName("cBox_product_8")
        self.cBox_product_9 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_9.setGeometry(QtCore.QRect(20, 510, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_9.setFont(font)
        self.cBox_product_9.setObjectName("cBox_product_9")
        self.cBox_product_10 = QtWidgets.QComboBox(self.frame_2)
        self.cBox_product_10.setGeometry(QtCore.QRect(20, 560, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_product_10.setFont(font)
        self.cBox_product_10.setObjectName("cBox_product_10")

        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(500, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_sales = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_sales.setGeometry(QtCore.QRect(570, 230, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_sales.setFont(font)
        self.lineEdit_sales.setObjectName("lineEdit_sales")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(540, 0, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.sBox_product_1 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_1.setGeometry(QtCore.QRect(340, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_1.setFont(font)
        self.sBox_product_1.setMaximum(999)
        self.sBox_product_1.setObjectName("sBox_product_1")
        self.sBox_product_2 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_2.setGeometry(QtCore.QRect(340, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_2.setFont(font)
        self.sBox_product_2.setMaximum(999)
        self.sBox_product_2.setObjectName("sBox_product_2")
        self.sBox_product_3 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_3.setGeometry(QtCore.QRect(340, 210, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_3.setFont(font)
        self.sBox_product_3.setMaximum(999)
        self.sBox_product_3.setObjectName("sBox_product_3")
        self.sBox_product_4 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_4.setGeometry(QtCore.QRect(340, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_4.setFont(font)
        self.sBox_product_4.setMaximum(999)
        self.sBox_product_4.setObjectName("sBox_product_4")
        self.sBox_product_5 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_5.setGeometry(QtCore.QRect(340, 310, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_5.setFont(font)
        self.sBox_product_5.setMaximum(999)
        self.sBox_product_5.setObjectName("sBox_product_5")
        self.sBox_product_6 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_6.setGeometry(QtCore.QRect(340, 360, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_6.setFont(font)
        self.sBox_product_6.setMaximum(999)
        self.sBox_product_6.setObjectName("sBox_product_6")
        self.sBox_product_7 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_7.setGeometry(QtCore.QRect(340, 410, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_7.setFont(font)
        self.sBox_product_7.setMaximum(999)
        self.sBox_product_7.setObjectName("sBox_product_7")
        self.sBox_product_8 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_8.setGeometry(QtCore.QRect(340, 460, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_8.setFont(font)
        self.sBox_product_8.setMaximum(999)
        self.sBox_product_8.setObjectName("sBox_product_8")
        self.sBox_product_9 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_9.setGeometry(QtCore.QRect(340, 510, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_9.setFont(font)
        self.sBox_product_9.setMaximum(999)
        self.sBox_product_9.setObjectName("sBox_product_9")
        self.sBox_product_10 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_product_10.setGeometry(QtCore.QRect(340, 560, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_product_10.setFont(font)
        self.sBox_product_10.setMaximum(999)
        self.sBox_product_10.setObjectName("sBox_product_10")
        self.sBox_sv_1 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_1.setGeometry(QtCore.QRect(400, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_1.setFont(font)
        self.sBox_sv_1.setMaximum(999)
        self.sBox_sv_1.setObjectName("sBox_sv_1")
        self.sBox_sv_2 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_2.setGeometry(QtCore.QRect(400, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_2.setFont(font)
        self.sBox_sv_2.setMaximum(999)
        self.sBox_sv_2.setObjectName("sBox_sv_2")
        self.sBox_sv_3 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_3.setGeometry(QtCore.QRect(400, 210, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_3.setFont(font)
        self.sBox_sv_3.setMaximum(999)
        self.sBox_sv_3.setObjectName("sBox_sv_3")
        self.sBox_sv_4 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_4.setGeometry(QtCore.QRect(400, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_4.setFont(font)
        self.sBox_sv_4.setMaximum(999)
        self.sBox_sv_4.setObjectName("sBox_sv_4")
        self.sBox_sv_5 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_5.setGeometry(QtCore.QRect(400, 310, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_5.setFont(font)
        self.sBox_sv_5.setMaximum(999)
        self.sBox_sv_5.setObjectName("sBox_sv_5")
        self.sBox_sv_6 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_6.setGeometry(QtCore.QRect(400, 360, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_6.setFont(font)
        self.sBox_sv_6.setMaximum(999)
        self.sBox_sv_6.setObjectName("sBox_sv_6")
        self.sBox_sv_7 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_7.setGeometry(QtCore.QRect(400, 410, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_7.setFont(font)
        self.sBox_sv_7.setMaximum(999)
        self.sBox_sv_7.setObjectName("sBox_sv_7")
        self.sBox_sv_8 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_8.setGeometry(QtCore.QRect(400, 460, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_8.setFont(font)
        self.sBox_sv_8.setMaximum(999)
        self.sBox_sv_8.setObjectName("sBox_sv_8")
        self.sBox_sv_9 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_9.setGeometry(QtCore.QRect(400, 510, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_9.setFont(font)
        self.sBox_sv_9.setMaximum(999)
        self.sBox_sv_9.setObjectName("sBox_sv_9")
        self.sBox_sv_10 = QtWidgets.QSpinBox(self.frame_2)
        self.sBox_sv_10.setGeometry(QtCore.QRect(400, 560, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sBox_sv_10.setFont(font)
        self.sBox_sv_10.setMaximum(999)
        self.sBox_sv_10.setObjectName("sBox_sv_10")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(408, 80, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btn_insert = QtWidgets.QPushButton(self.frame_2, clicked=self.insert_Sales)
        self.btn_insert.setGeometry(QtCore.QRect(560, 340, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_insert.setFont(font)
        self.btn_insert.setAutoDefault(False)
        self.btn_insert.setDefault(False)
        self.btn_insert.setFlat(False)
        self.btn_insert.setObjectName("btn_insert")
        self.dateEdit_sub_1 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_sub_1.setGeometry(QtCore.QRect(60, 550, 121, 41))
        self.dateEdit_sub_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateEdit_sub_1.setDate(QtCore.QDate.currentDate())
        self.dateEdit_sub_1.wheelEvent = lambda event: None
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_sub_1.setFont(font)
        self.dateEdit_sub_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_sub_1.setReadOnly(False)
        self.dateEdit_sub_1.setCalendarPopup(True)
        self.dateEdit_sub_1.setObjectName("dateEdit_sub_1")
        self.dateEdit_sub_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_sub_2.setGeometry(QtCore.QRect(230, 550, 121, 41))
        self.dateEdit_sub_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateEdit_sub_2.setDate(QtCore.QDate.currentDate())
        self.dateEdit_sub_2.wheelEvent = lambda event: None
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_sub_2.setFont(font)
        self.dateEdit_sub_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_sub_2.setReadOnly(False)
        self.dateEdit_sub_2.setCalendarPopup(True)
        self.dateEdit_sub_2.setObjectName("dateEdit_sub_2")
        
        self._today_button = QtWidgets.QPushButton('&오늘', clicked=self.setToday)
        self.dateEdit_main.calendarWidget().layout().addWidget(self._today_button)
        self._today_button_sub_1 = QtWidgets.QPushButton('&오늘', clicked=self.setToday_sub_1)
        self.dateEdit_sub_1.calendarWidget().layout().addWidget(self._today_button_sub_1)
        self._today_button_sub_2 = QtWidgets.QPushButton('&오늘', clicked=self.setToday_sub_2)
        self.dateEdit_sub_2.calendarWidget().layout().addWidget(self._today_button_sub_2)
        
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(184, 556, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.btn_wrapup = QtWidgets.QPushButton(self.centralwidget, clicked = self.wrapup)
        self.btn_wrapup.setGeometry(QtCore.QRect(120, 630, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_wrapup.setFont(font)
        self.btn_wrapup.setAutoDefault(False)
        self.btn_wrapup.setDefault(False)
        self.btn_wrapup.setFlat(False)
        self.btn_wrapup.setObjectName("btn_wrapup")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 700, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(240, 700, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(240, 730, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(240, 760, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")

        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(240, 790, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(410, 660, 741, 171))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_management = QtWidgets.QPushButton(self.frame_3, clicked = self.open_management)
        self.btn_management.setGeometry(QtCore.QRect(20, 10, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_management.setFont(font)
        self.btn_management.setAutoDefault(False)
        self.btn_management.setDefault(False)
        self.btn_management.setFlat(False)
        self.btn_management.setObjectName("btn_management")
        self.btn_details = QtWidgets.QPushButton(self.frame_3, clicked = self.open_details)
        self.btn_details.setGeometry(QtCore.QRect(160, 10, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_details.setFont(font)
        self.btn_details.setAutoDefault(False)
        self.btn_details.setDefault(False)
        self.btn_details.setFlat(False)
        self.btn_details.setObjectName("btn_details")
        self.btn_product_details = QtWidgets.QPushButton(self.frame_3, clicked = self.open_product_details)
        self.btn_product_details.setGeometry(QtCore.QRect(160, 90, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_product_details.setFont(font)
        self.btn_product_details.setAutoDefault(False)
        self.btn_product_details.setDefault(False)
        self.btn_product_details.setFlat(False)
        self.btn_product_details.setObjectName("btn_product_details")
        self.btn_final = QtWidgets.QPushButton(self.frame_3, clicked = self.open_final)
        self.btn_final.setGeometry(QtCore.QRect(300, 10, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_final.setFont(font)
        self.btn_final.setAutoDefault(False)
        self.btn_final.setDefault(False)
        self.btn_final.setFlat(False)
        self.btn_final.setObjectName("btn_final")
        self.btn_card_details = QtWidgets.QPushButton(self.frame_3, clicked = self.open_card_details)
        self.btn_card_details.setGeometry(QtCore.QRect(300, 90, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_card_details.setFont(font)
        self.btn_card_details.setAutoDefault(False)
        self.btn_card_details.setDefault(False)
        self.btn_card_details.setFlat(False)
        self.btn_card_details.setObjectName("btn_card_details")
        
        self.btn_branch = QtWidgets.QPushButton(self.frame_3, clicked = self.open_branch)
        self.btn_branch.setGeometry(QtCore.QRect(440, 10, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_branch.setFont(font)
        self.btn_branch.setAutoDefault(False)
        self.btn_branch.setDefault(False)
        self.btn_branch.setFlat(False)
        self.btn_branch.setObjectName("btn_branch")
        
        self.btn_branch_details = QtWidgets.QPushButton(self.frame_3, clicked = self.open_branch_details)
        self.btn_branch_details.setGeometry(QtCore.QRect(440, 90, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_branch_details.setFont(font)
        self.btn_branch_details.setAutoDefault(False)
        self.btn_branch_details.setDefault(False)
        self.btn_branch_details.setFlat(False)
        self.btn_branch_details.setObjectName("btn_branch_details")
        
        self.btn_bonsa = QtWidgets.QPushButton(self.frame_3, clicked = self.open_bonsa)
        self.btn_bonsa.setGeometry(QtCore.QRect(580, 10, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bonsa.setFont(font)
        self.btn_bonsa.setAutoDefault(False)
        self.btn_bonsa.setDefault(False)
        self.btn_bonsa.setFlat(False)
        self.btn_bonsa.setObjectName("btn_bonsa")
        
        self.btn_bonsa_details = QtWidgets.QPushButton(self.frame_3, clicked = self.open_bonsa_details)
        self.btn_bonsa_details.setGeometry(QtCore.QRect(580, 90, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bonsa_details.setFont(font)
        self.btn_bonsa_details.setAutoDefault(False)
        self.btn_bonsa_details.setDefault(False)
        self.btn_bonsa_details.setFlat(False)
        self.btn_bonsa_details.setObjectName("btn_bonsa_details")
        
        
        self.btn_add = QtWidgets.QPushButton(self.centralwidget, clicked = self.open_add)
        self.btn_add.setGeometry(QtCore.QRect(1130, 770, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setAutoDefault(False)
        self.btn_add.setDefault(False)
        self.btn_add.setFlat(False)
        self.btn_add.setObjectName("btn_add")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1340, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.cboxs = [self.cBox_product_1, self.cBox_product_2, self.cBox_product_3, self.cBox_product_4, self.cBox_product_5,
                      self.cBox_product_6, self.cBox_product_7, self.cBox_product_8, self.cBox_product_9, self.cBox_product_10]
        self.sboxs = [self.sBox_product_1, self.sBox_product_2, self.sBox_product_3, self.sBox_product_4, self.sBox_product_5, 
                      self.sBox_product_6, self.sBox_product_7, self.sBox_product_8, self.sBox_product_9, self.sBox_product_10]
        self.sboxs_sv = [self.sBox_sv_1, self.sBox_sv_2, self.sBox_sv_3, self.sBox_sv_4, self.sBox_sv_5, 
                         self.sBox_sv_6, self.sBox_sv_7, self.sBox_sv_8, self.sBox_sv_9, self.sBox_sv_10]
        self.lines = [self.lineEdit_cashin, self.lineEdit_cardin, self.lineEdit_refund]
        for i in self.cboxs:
            i.wheelEvent = lambda event: None
        for i in self.sboxs:
            i.wheelEvent = lambda event: None
        for i in self.sboxs_sv:
            i.wheelEvent = lambda event: None
        self.cBox_name.wheelEvent = lambda event: None
        self.cBox_cardkind.wheelEvent = lambda event: None
        
        for i in self.sboxs:
            i.valueChanged['int'].connect(self.calc_Product)
        for i in self.sboxs_sv:
            i.valueChanged['int'].connect(self.calc_Product)
        
        for i in self.cboxs:
            i.currentIndexChanged['int'].connect(self.calc_Product)
        
        for i in self.lines:
            i.editingFinished.connect(self.set_lineEdit)
        
        self.load_list()
        
        self.lineEdit_cardin.setValidator(QtGui.QIntValidator())
        self.lineEdit_cashin.setValidator(QtGui.QIntValidator())
        self.lineEdit_refund.setValidator(QtGui.QIntValidator())
        self.lineEdit_sales.setValidator(QtGui.QIntValidator())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "예림지사 관리 프로그램"))
        self.label_2.setText(_translate("MainWindow", "이름:"))
        self.label_3.setText(_translate("MainWindow", "현금입금:"))
        self.label_4.setText(_translate("MainWindow", "카드입금:"))
        self.label_5.setText(_translate("MainWindow", "승인번호:"))
        self.label_6.setText(_translate("MainWindow", "제품반품:"))
        self.label_7.setText(_translate("MainWindow", "기타:"))
        self.lineEdit_cashin.setText(_translate("MainWindow", "0"))
        self.lineEdit_cardin.setText(_translate("MainWindow", "0"))
        self.lineEdit_refund.setText(_translate("MainWindow", "0"))
        self.btn_reset.setText(_translate("MainWindow", "초기화"))
        self.label_8.setText(_translate("MainWindow", "매출액:"))
        self.lineEdit_sales.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", self.today))
        self.label_10.setText(_translate("MainWindow", "s/v"))
        self.btn_insert.setText(_translate("MainWindow", "입력"))
        self.label_11.setText(_translate("MainWindow", "~"))
        self.btn_wrapup.setText(_translate("MainWindow", "기간매출 및 입금"))
        self.label_12.setText(_translate("MainWindow", "총매출:"))
        self.label_13.setText(_translate("MainWindow", "총입금:"))
        self.label_14.setText(_translate("MainWindow", "현금입금:"))
        self.label_15.setText(_translate("MainWindow", "카드입금:"))
        self.label_16.setText(_translate("MainWindow", "반품처리:"))
        self.btn_management.setText(_translate("MainWindow", "재고관리"))
        self.btn_details.setText(_translate("MainWindow", "내역"))
        self.btn_product_details.setText(_translate("MainWindow", "재고내역"))
        self.btn_final.setText(_translate("MainWindow", "정산"))
        self.btn_branch.setText(_translate("MainWindow", "지사출고"))
        self.btn_branch_details.setText(_translate("MainWindow", "지사내역"))
        self.btn_card_details.setText(_translate("MainWindow", "카드내역"))
        self.btn_bonsa.setText(_translate("MainWindow", "본사입고"))
        self.btn_bonsa_details.setText(_translate("MainWindow", "본사내역"))
        self.btn_add.setText(_translate("MainWindow", "제품추가"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
